### ISSUE TITLE
Build NLDAS hosting subset pipeline for domain

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#1]
_could_ include intermediate data optimization and re-writes

**Comment by jread-usgs** [comment]
Once we get past the auth part, we'll want `	dods://hydro1.gesdisc.eosdis.nasa.gov/dods/NLDAS_FORA0125_H.002
`

**Comment by jread-usgs** [comment]
configure locally:
- [ ] .netrc
- [ ] .urs_cookies 
- [ ] .dodsrc

from: http://hdfeos.org/software/ncl_opendap_mls.php

**Comment by jread-usgs** [comment]
If configured properly, this should run fine: 
```
nccopy -m 15m http://hydro1.sci.gsfc.nasa.gov/dods/NLDAS_FORA0125_H.002?lon[0:1:223],lat[0:1:163],time[0:1:15],pressfc[0:1:15][0:1:163][0:1:223] example.nc
```

**Comment by jread-usgs** [comment]
[NLDAS data rods](https://hydro1.gesdisc.eosdis.nasa.gov/daac-bin/access/timeseries.cgi?variable=NLDAS:NLDAS_FORA0125_H.002:DSWRFsfc&location=NLDAS:X304-Y071&startDate=1979-01-02T00&endDate=1981-05-20T23&type=asc2) is another option, but it has a [water mask](https://ldas.gsfc.nasa.gov/nldas/asc/NLDASmask_UMDunified.asc) that will cause trouble for big lakes and potentially lakes close to the Great Lake shorelines.

**Comment by jread-usgs** [comment]
Seems bypassing the GDP processing is a better solution, and avoiding a generic/reusable hosting of these timeseries data is practical at this point. Future needs for projects (e.g., 2WP) are expected to be covered in a more robust way w/ CONUS coverage.

Proposal:
1) timeseries driver files are written as `feather` files, which can be written to csv on demand when models are run. This format will be small locally, easy to open and append to, and readable/writeable by R and python
2) we'll ditch the intermediate netcdf file chunks. I don't see a good reason to keep them around, other than to avoid future downloads, and their size adds up
3) variables will be converted into input variables with proper units, but keep the native timestep (hourly). Downsampling to a less frequent timestep can be done on the fly as a pre-model step if necessary. Seeming increasingly likely we'll be running the model at an hourly timestep anyhow
4) full builds of feather files will happen locally, and then we'll have a later state to rsync (or other) them over to the modeling environment. I won't be dealing with an intermediate storage location for this application, although some of the `RDS` offerings are appealing. Or this workflow will be run _from_ the computing environment, so no need to rsync
5) hopefully I can have a `scipiper` target for each driver file (which will have 7 variables + time) that is tied to an NLDAS cell. 

Discussed this w/ @aappling-usgs and came up with the following:

There is a main remake file that orchestrates the interactions between a configuration file/target and two task plan remake files, one for the "data cubes" and the other for the feather files. The feather files will create a secondary config that is the result of the processing. A diff between the main config and this one will be used to figure out if new data cubes need to be downloaded. 

The config is a set of times and unique cells that we need data from and a rule for temporal chunk size. So if we add a new location from a cell we have data from, we don't pull anything new. If we add new locations that don't have data, the data cube specifications will be updated and those jobs will start fresh. 

There are some challenging bits to work out here. Namely, the inventory of feather files is kind of an input to the data cub config (we don't want to pull data that we already have), but this is a cyclical dependency. So we have to work in a hidden dependency in a way that makes sense and won't cause trouble...

For starters, I will create a very small spatial domain, a small time range, and a small temporal chunk stride so that I deal w/ the challenge of > 1 cube per variable, w/ different times. I will test to make sure changes are dealt with appropriately for downloads and feather builds. Then scale it up.

**Comment by jread-usgs** [comment]
for future self, keeping the .nc data in memory while streaming is much more fault tolerant. So revise flag to:
```
nccopy -w http://hydro1.sci.gsfc.nasa.gov/dods/NLDAS_FORA0125_H.002?lon[0:1:223],lat[0:1:163],time[0:1:15],pressfc[0:1:15][0:1:163][0:1:223] example.nc
```
per [nccopy document](https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_utilities_guide.html#guide_nccopy)

**Comment by jread-usgs** [comment]
Some questions that are coming up w/ this part of the pipeline:

1) ~is it OK to drop the nc time dimension when getting data for multiple variables from NLDAS? We are currently using `nccopy` on a single variable at a time for a chunk of the total desired time range. We have a check at the end of the `nccopy` to verify we have the right number of steps, and aren't really joining actual time until later (currently, just using indices).~ is not worth it, time is a vector and is small ( < 0.1% of 3D data). 
2) how to generate the cell-specific data from the chunked "cubes". We want to make this somewhat efficient, but we can't read all chunks into memory at once (which would make it easy to write cells quickly that are complete in the time dimension). Some alternatives: read a group of chunks into memory at once, and write larger time-chunked cells, _or_ pay the nc_open/close overhead for every cell and every variable to build complete cells, _or_ make the chunks look continuous in time, a la THREDDS (but is this actually faster, or would the same read limits impact THREDDS?) 
3) how many intermediate data stages we use. Chunks of .nc make sense, they are the raw data. But how many more intermediate (and potentially duplicative) data stages should we have before arriving on a merged and downsampled (in time, if appropriate) since cell file? I think I would suggest we have a single intermediate in between .nc and final multi-var cell file. The intermediate would either be time-chunked (but longer, see `2` above) single-var cell data, or time complete single-var cell data. The latter would make it easier on the following step, since it would only need to aggregate across variables, instead of variables and times.

**Comment by jread-usgs** [comment]
For question 2 I set up the following quick experiment:

```r

library(ncdf4)
files <- c('7_drivers_fetch/out/NLDAS_time[0.4999]_y[132.196]_x[221.344]_var[dswrfsfc].nc', 
           '7_drivers_fetch/out/NLDAS_time[5000.9999]_y[132.196]_x[221.344]_var[dswrfsfc].nc',
           '7_drivers_fetch/out/NLDAS_time[10000.14999]_y[132.196]_x[221.344]_var[dswrfsfc].nc',
           '7_drivers_fetch/out/NLDAS_time[15000.19999]_y[132.196]_x[221.344]_var[dswrfsfc].nc')

cell.x <- c(123, 2)
cell.y <- c(1, 64)

cell_data <- data.frame(v1 = rep(NA_real_, 20000), v2 = rep(NA_real_, 20000))
# option A: open several .nc files into memory, get data for several cells, close .nc files:

var <- 'dswrfsfc'

system.time({
  nc1 <- nc_open(files[1])
  nc2 <- nc_open(files[2])
  nc3 <- nc_open(files[3])
  nc4 <- nc_open(files[4])
  
  cell_data$v1[1:5000] <- ncvar_get(nc1, varid = var, start = c(cell.x[1], cell.y[1], 1), count = c(1, 1, -1))
  cell_data$v2[1:5000] <- ncvar_get(nc1, varid = var, start = c(cell.x[2], cell.y[2], 1), count = c(1, 1, -1))
  
  cell_data$v1[5001:10000] <- ncvar_get(nc2, varid = var, start = c(cell.x[1], cell.y[1], 1), count = c(1, 1, -1))
  cell_data$v2[5001:10000] <- ncvar_get(nc2, varid = var, start = c(cell.x[2], cell.y[2], 1), count = c(1, 1, -1))
  
  cell_data$v1[10001:15000] <- ncvar_get(nc3, varid = var, start = c(cell.x[1], cell.y[1], 1), count = c(1, 1, -1))
  cell_data$v2[10001:15000] <- ncvar_get(nc3, varid = var, start = c(cell.x[2], cell.y[2], 1), count = c(1, 1, -1))
  
  cell_data$v1[15001:20000] <- ncvar_get(nc4, varid = var, start = c(cell.x[1], cell.y[1], 1), count = c(1, 1, -1))
  cell_data$v2[15001:20000] <- ncvar_get(nc4, varid = var, start = c(cell.x[2], cell.y[2], 1), count = c(1, 1, -1))
  
  nc_close(nc1)
  nc_close(nc2)
  nc_close(nc3)
  nc_close(nc4)
})


# option B: open and close .nc files for each cell access
cell_data <- data.frame(v1 = rep(NA_real_, 20000), v2 = rep(NA_real_, 20000))
system.time({
  
  nc <- nc_open(files[1])
  cell_data$v1[1:5000] <- ncvar_get(nc, varid = var, start = c(cell.x[1], cell.y[1], 1), count = c(1, 1, -1))
  cell_data$v2[1:5000] <- ncvar_get(nc, varid = var, start = c(cell.x[2], cell.y[2], 1), count = c(1, 1, -1))
  nc_close(nc)
  
  nc <- nc_open(files[2])
  cell_data$v1[5001:10000] <- ncvar_get(nc, varid = var, start = c(cell.x[1], cell.y[1], 1), count = c(1, 1, -1))
  cell_data$v2[5001:10000] <- ncvar_get(nc, varid = var, start = c(cell.x[2], cell.y[2], 1), count = c(1, 1, -1))
  nc_close(nc)
  
  nc <- nc_open(files[3])
  cell_data$v1[10001:15000] <- ncvar_get(nc, varid = var, start = c(cell.x[1], cell.y[1], 1), count = c(1, 1, -1))
  cell_data$v2[10001:15000] <- ncvar_get(nc, varid = var, start = c(cell.x[2], cell.y[2], 1), count = c(1, 1, -1))
  nc_close(nc)
  
  nc <- nc_open(files[4])
  cell_data$v1[15001:20000] <- ncvar_get(nc, varid = var, start = c(cell.x[1], cell.y[1], 1), count = c(1, 1, -1))
  cell_data$v2[15001:20000] <- ncvar_get(nc, varid = var, start = c(cell.x[2], cell.y[2], 1), count = c(1, 1, -1))
  nc_close(nc)
})
```
The results seem to be approximately the same for both approaches, which is surprising. Both come in at ~ 0.7 seconds. In one case the second approach took 3 seconds, but I wasn't able to pin down why or reproduce it. I started new R sessions for each case.

**Comment by jread-usgs** [comment]
From Blodgett: 
> One thing is the nc_open has an option to not read coordinate variables. If you don't need them that will save a lot of time and memory overhead in the nc object

**Comment by jread-usgs** [comment]
Approach for this task (copied from a PR comment):
![image](https://user-images.githubusercontent.com/2349007/43284079-5e6be612-90e0-11e8-8aad-e8a8c80c9259.png)

**Comment by jread-usgs** [comment]
well, next on the list of frustrating issues: `nccopy -w` vs`nccopy -m 15m` causes some file transfers that have zeros for the values...
switching back to `nccopy -m 15m` now

**Comment by jread-usgs** [comment]
update - `-m 15m` has those issues too. Not sure which is more common, but switching back to -w

**Comment by jread-usgs** [comment]
David W notes that
> Adding `-d[1-9]` should compress the output of your nccopy which you may want to do anyways
max compression (-d9) cut the file size by 60% on the good file that you posted

**Comment by jread-usgs** [comment]
pipeline for getting the data and building the cells is chugging along. Now working on the "lake to cell" crosswalk. I was able to build the cells for the NLDAS data using `sf::st_make_grid` and the next step is matching lakes to their cells, and then using that set of cells to both build the .nc query and to determine which cell feather files are built (and how they are mapped to individual lake IDs). 

a plot of the 2017 modeling domain w/ cells: 
![image](https://user-images.githubusercontent.com/2349007/43721641-fc8e93b4-9958-11e8-8210-d803d667e9c5.png)

I'd expect we'll end up only needing ~50% of the cells included in the .nc bounding box (useful for data size calcs), but we'll have a better estimate when we use the actual lake shapefile to match against the cells.

**Comment by jread-usgs** [comment]
If I did this initial cross-walk correctly, I count 2,018 NLDAS cells contain lake centroids from the 2017 data release:

![image](https://user-images.githubusercontent.com/2349007/43727567-fa5da418-9967-11e8-9283-e26e1805a317.png)

**Comment by aappling-usgs** [comment]
Looks a lot more practical than downloading all the red cells!

**Comment by jread-usgs** [comment]
The current build will fail when cubes are set up to just take one cell (the sequence for x and y get an error)

this is the example when we add maybe a single lake in the future, so it should be supported if possible. E.g.,:
```yaml
  nldas_cells:
    command: list(x=I(c(347)), y=I(c(23)), variables=I(c('dlwrfsfc','pressfc','apcpsfc','vgrd10m','ugrd10m','dswrfsfc','spfh2m','tmp2m'))) 
```

**Comment by jread-usgs** [comment]
For some reason I needed to re-gen the cookies file to get this working again...huh
