### ISSUE TITLE
depth/date duplicates

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#123]
some date/depth pairs have more than one row for a lake. We'll need a summarize before the date/depth count

**Comment by limnoliver** [comment]
Hmmm - so we must need another reduction [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/7b_temp_merge/src/merge_all_temp_dat.R#L267)

**Comment by jread-usgs** [comment]
Yes, something like
```r
group_by(site_id, date, depth) %>% summarise(temp = mean(temp))
```

**Comment by limnoliver** [comment]
I removed all uses of `mean` in the last iteration, and instead tried to be more consistent with site selection (e.g., choosing the preferred site or source when it was available in a situation where there were multiple obs per date/depth). I'm guessing there are relatively few data/depth duplicates at this point, so maybe mean is a fine solution.
