### ISSUE TITLE
Estimate GLM TOHA

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temperature-model-prep#138]
Estimate TOHA from GLM model output for all lakes and dates with Kelsey help. Uses code from #136 to calc TOHA. From [TOHA task table doc](https://docs.google.com/spreadsheets/d/1KY_CNCLbuC1-bxLet6GOzYKGy6YlnI0AGOII4Yoez2Y/edit#gid=0). Requires GLM run to be finished (which Jordan is doing).

Due 4/27. Not sure if it should be in this repo or not.

**Comment by jread-usgs** [comment]
Or this repo: https://github.com/USGS-R/lake-temperature-out

**Comment by lindsayplatt** [comment]
Jordan built these using the [lake-temperature-out repo](https://github.com/USGS-R/lake-temperature-out) between 4/18 - 4/19. The outputs are prefixed with `pgdl` on Science Base: https://www.sciencebase.gov/catalog/item/5e774355e4b01d509270e2a1. Next steps are to have Kelsey verify the outputs before we can call this complete.

**Comment by jread-usgs** [comment]
Moved this to [lake-temperature-out repo](https://github.com/USGS-R/lake-temperature-out). Closing here.
