### ISSUE TITLE
figure out what is limiting us from including Isle Royale lakes

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#176]
![image](https://user-images.githubusercontent.com/2349007/88332813-ca84aa80-ccf4-11ea-86fd-69ef3863b592.png)

We've got these lakes in the canonical set
```r
scipiper::scmake('1_crosswalk_fetch/out/canonical_lakes_sf.rds', remake_file = '1_crosswalk_fetch.yml') %>%
    readRDS %>% st_transform(crs = "+init=epsg:2811") %>% sf::st_simplify(dTolerance = 40) %>% 
    st_geometry() %>% plot(xlim = c(1154146.6, 1254146.6), ylim = c(434257.8, 464257.8))
```

Are we missing depth, drivers, clarity etc?

We should have temperature data on these lakes as there are loggers. But not sure where that gets linked

**Comment by jread-usgs** [comment]
Gretchen found data by contacting NPS. I have uploaded the zip they shared into `3_params_fetch/in/ISRO_GLKN_Bathymetric_FinalData.zip.` and used `gd_confirm_posted('3_params_fetch/in/ISRO_GLKN_Bathymetric_FinalData.zip.ind')` to create the indicator file of the upload. 

I quick look at this: Looks like a geodatabase with 24 lakes. Some lakes are multipolygons, which I'd guess makes it easier to calculate contour areas, but some are multipolylines, which I'd guess means they have a break in the contour ring(s) somewhere, which makes it hard or we need to make assumpations. 

```r
st_layers('3_params_fetch/in//ISRO_GLKN_BathymetricData.gdb/')
Driver: OpenFileGDB 
Available layers:
                 layer_name     geometry_type features fields
1         Richie_1mContours Multi Line String       33      3
2    Chickenbone_1mContours Multi Line String       32      4
3        Sargent_1mContours Multi Line String       38      4
4         Harvey_1mContours Multi Line String       50      4
5         Beaver_1mContours Multi Line String       31      4
6          Beaver_CntrPolys     Multi Polygon       31      8
7      Ahmik_HalfM_Contours Multi Line String        6      4
8     George_HalfM_Contours Multi Line String       15      4
9  Feldtmann_HalfM_Contours Multi Line String       36      4
10      Siskiwit_2mContours Multi Line String      132      3
11         Siskiwit_6m_Poly     Multi Polygon       47      9
12         Desor_1mContours Multi Line String      101      4
13        LeSage_1mContours Multi Line String       29      4
14          Ahmik_CntrPolys     Multi Polygon        6      8
15    Chickenbone_CntrPolys     Multi Polygon       32      8
16         LeSage_CntrPolys     Multi Polygon       29      8
17      Feldtmann_CntrPolys     Multi Polygon       36      8
18         George_CntrPolys     Multi Polygon       15      8
19         Harvey_CntrPolys     Multi Polygon       50      8
20          Desor_CntrPolys     Multi Polygon       43      8
21         Richie_CntrPolys     Multi Polygon       33      8
22        Sargent_CntrPolys     Multi Polygon       37      8
23   Epidote_HalfM_Contours Multi Line String       13      4
24        Epidote_CntrPolys     Multi Polygon       13      8
```
Plotting the first of these

![image](https://user-images.githubusercontent.com/2349007/102530996-506c0e00-4067-11eb-8e1a-193cf1812bb6.png)

**Comment by lindsayplatt** [comment]
Low-hanging fruit: crosswalk these to nhdhr then only do ones that are multipolygons (example of this is ND bathy). Log another issue for the multipolylines ones for later.

**Comment by jread-usgs** [comment]
I dug into this a tiny bit more this morning and realized that the other features in the geodatabase are just different versions of the same lakes that we've just added, so the low-hanging fruit is all of the fruit and this is what we ended up with:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/2349007/163850346-245a5e68-7442-4d52-aad8-6c812de3b9c7.png">

I will close this issue
