### ISSUE TITLE
Add MO lakes/reservoirs for Fish Productivity project

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#181]
For MO DNR, 

Some lakes will be referenced to the `WBID`:
> Water body identification number (WBID) unique to each water body or water body segment listed in the tables of the State Water Quality Standards. WBID number stored as numeric field

Some GIS resources [here](http://msdis-archive.missouri.edu/archive/Missouri_Vector_Data/Inland_Water_Resources/)

No clear bulk source of depth/bathymetry as of now

Plenty of WQP data for secchi and temperature

**Comment by jread-usgs** [comment]
See @limnoliver's GH issue for DRB [here](https://github.com/USGS-R/delaware-model-prep/issues/78)

Will revise this issue to take on a similar format in the future.

**Comment by limnoliver** [comment]
Being nosy here to say LAGOS probably has max depth for these reservoirs.

**Comment by jread-usgs** [comment]
Not nosy at all! public repo and I tagged your GH handle 😆

**Comment by jread-usgs** [comment]
@limnoliver 

Here are the LAGOS depths that are in the pipeline now
![image](https://user-images.githubusercontent.com/2349007/101651005-334d9480-3a02-11eb-9277-0320c9127801.png)

```r
library(sf)
library(tidyverse)
lake_centroids <- readRDS('2_crosswalk_munge/out/centroid_lakes_sf.rds')
filter(lake_centroids, site_id %in% readRDS('4_params_munge/out/lagos_depths.rds')$site_id) %>% 
   st_geometry() %>% plot(pch = 16, cex = 0.5)
```

I wonder if I've getting some kind of filtered version of the depths that don't have all of the states? The original fetch went to https://portal.edirepository.org/nis/dataviewer?packageid=edi.101.3&entityid=df2f94197ed33bc6f3052511b23a721e

Surprised I don't have MO or any of the NE states that were pulled in once I expanded the footprint to include the DRB..

**Comment by limnoliver** [comment]
Yeah, weird. This is the lat/long of all lakes with maxdepth from ^ that link: 
![image](https://user-images.githubusercontent.com/15788176/101652587-08fcd680-3a04-11eb-979e-5432f80fca4e.png)

**Comment by jread-usgs** [comment]
hahaha, here is the culprit:
```yaml
  1_crosswalk_fetch/out/LAGOS_lakes_sf.rds.ind:
    command: LAGOS_zip_to_sf(
      out_ind = target_name,
      layer = I("LAGOS_NE_All_Lakes_4ha"),
      zip_ind = '1_crosswalk_fetch/in/LAGOS_NE_All_Lakes_4ha.zip.ind',
      states = I(c("IA", "IN", "SD", "ND", "MI", "MN", "WI", "IL")))
```

**Comment by limnoliver** [comment]
Well, that's one of the easiest fixes I've seen!

**Comment by jread-usgs** [comment]
open PR #191 addresses part of the oversight here and automatically added a bunch of MO lakes/res

![image](https://user-images.githubusercontent.com/2349007/101791296-fc8e8180-3ac8-11eb-991e-f6b202486c62.png)

**Comment by jread-usgs** [comment]
Yes, I think we can close this since it wasn't a very carefully worded issue to start with :)
But we'll probably want to set up more specific issues in the future if we're in need of certain kinds of data for these reservoirs that we don't have yet.
