### ISSUE TITLE
Fix multiple obs per reservoir-date-depth

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#203]
Jordan noted there are multiple observations per reservoir-date-depth in the [Cannonsville/Pepacton temperature dataset](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/7b_temp_merge.yml#L76). Investigate and get down to a single obs per reservoir-date-depth.

**Comment by RAtshan** [comment]
After investigating the NYC_DEP reservoir raw data, I found that there're multiple temperature measurements per reservoir-date-depth. To fix the issue I found the average temperature per reservoir-source-date-depth. (#204 )
