### ISSUE TITLE
Add new MN DNR data collated by Holly

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#206]
There is a new 1945-2021 all MNDNR Temp/DO dataset in the [`in`](https://drive.google.com/drive/u/0/folders/1dutCiFEOoRObXLn6n3BRKhZDDAijK65Q) folder

We'll need to get a new parser set up for this and get it integrated into the project.

**Comment by jread-usgs** [comment]
Parsers are [here](https://github.com/USGS-R/lake-temperature-model-prep/tree/master/7a_temp_coop_munge/src/data_parsers) but I think Sam is the main person w/ experience adding a new coop file. May need to check w/ her.

**Comment by limnoliver** [comment]
Here's a [how-to](https://docs.google.com/document/d/1Z1fg8ng9IWHS9oiQTxsDvpGBlbgz2bMZ5rWNxfRiHC8/edit#heading=h.5ajsuzlpviwv)!

**Comment by jread-usgs** [comment]
Very helpful Sam!

**Comment by jread-usgs** [comment]
This is included in #211
