### ISSUE TITLE
Bring in Navico temperature data

### ISSUE THREAD

**Issue by hcorson-dosch** [USGS-R/lake-temperature-model-prep#219]
Incorporate the [Navico lake temperature data](https://docs.google.com/spreadsheets/d/1bw_Kett2A6WcbYQNjB2jYFof2EkLtrKX/edit?usp=sharing&ouid=100995528200180469387&rtpof=true&sd=true) into the pipeline.

Initial notes:
* The data are from lakes in 11 states (AR, IL, IN, IA, MI, MN, MO, ND, OH, SD, WI)
* The temperature fields are average, maximum, and minimum water temp
* The data includes averages over varying timescales (all time, each year, each month, each day) that will need to be filtered out - there are separate columns for Year, Month, Day, Hour, which are noted as 'All' when data is averaged over the corresponding period
* No depth is included - we're assuming these are surface temperatures taken with a thermistor sensor attached to a sonar unit on a boat
* The data are in separate state-specific tabs within an Excel spreadsheet
* Waterbody latitude and longitude are provided, as are waterbody name and the Navico MapWaterbodyID. We should hopefully be able to use this last ID  (renamed to Navico ID in this pipeline) to match to the previously incorporated Navico max and mean depth data.
* From a quick glance, looks like there may sometimes be >1 site per lake, named differently by waterbody name and (I think) MapWaterbodyID (renamed to Navico ID in this pipeline)

**Comment by jread-usgs** [comment]
Please change the link to our gdrive `in` place for this file so that it remains unshared publicly.
