### ISSUE TITLE
Expand LAGOS dataset from LAGOS-NE to LAGOS-US? Spatial and depth data available

### ISSUE THREAD

**Issue by hcorson-dosch** [USGS-R/lake-temperature-model-prep#220]
Currently, the [pipeline is using](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/1_crosswalk_fetch.yml#L72-L77) the [LAGOS-NE database](https://drive.google.com/file/d/1gi7Boceim5UCLAYHs694dsXF2pU26lhC/view?usp=sharing) of [lakes >= 4ha](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=98&revision=4), which [does not include](https://pubs.er.usgs.gov/publication/70196469) AR, SD, or ND lakes:

![image](https://user-images.githubusercontent.com/54007288/137348338-1afeecbf-3339-4177-86a3-406905230ff7.png)

It also uses [LAGOS depth data](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/4_params_munge.yml#L90) from the `lakeslimno10873.csv` file and [LAGOS secchi data](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/4_params_munge.yml#L85) from the `epi_waterquality10873.csv` file, both in the [LAGOS-NE LIMNO dataset](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.101.3)

In August 2021, the [LAGOS-US database was released](https://lagoslakes.org/lagos-us-overview/), which covers the conterminous US:
![image](https://user-images.githubusercontent.com/54007288/137350574-f6af97bc-27b5-4e93-ac27-578fb437342c.png)

The spatial data associated with the LAGOS-US LOCUS module is available [here](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.854.1), in the `lake.shp` shapefile within the `gis_locus_v1.0.gdb` geodatabase within `gis_locus_v1.0_gdb.zip`. The switch would be pretty easy, but it does look like some attribute names have changed (e.g., lagos id, state).

According to the [overview](https://lagoslakes.org/lagos-us-overview/), depth data (LAGOS-US LAKE DEPTH) was expected September 2021, and secchi data (contained in LAGOS-US LIMNO) isn't expected to be available until summer 2022.

So for now, adding LAGOS-US would get us spatial data for more states in our footprint (AR, ND, SD), but not yet depth or secchi data, though depth at least may be available soon.

**Comment by jread-usgs** [comment]
Depth has arrived :tada: https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=1043&revision=1

**Comment by limnoliver** [comment]
Nice to see a broad-scale estimate of depth coverage to cite: 

`...contains in situ measurements of lake depth for a subset of all lakes (n = 17,675) in the conterminous U.S. > 1 ha (3.7% of 479,950) that are in the LAGOS-US...`

**Comment by lindsayplatt** [comment]
@jread-usgs - I am currently working on replacing the LAGOS_NE depths in the pipeline with the LAGOS_US depths. Confused about how to actually get the depths file into the google drive. The LAGOS_NE one is within `3_params_fetch/out/` which indicates that it has a target that produces it, but I can't find one. There is [a `fetch_LAGOS_NE_depths()` function](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/3_params_fetch/src/fetch_LAGOS.R#L3) that looks like what I should be using, but it isn't actually used anywhere in the pipeline. Seems like something is slightly off here.

**Comment by lindsayplatt** [comment]
Switch from LAGOS-NE to LAGOS-US for depth data completed with #329! Closing this and moving the potential for expanding the clarity data within #163 instead.
