### ISSUE TITLE
Bring in Norfolk_* temperature data

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#232]
Norfolk_* data set consists of ten files for two locations at the ***Norfork*** Reservoir Dam in northern Arkansas: the dam site and highway bridge 62. Data for both sites was collected on a monthly basis from 2016-2020 and was received from AR Fish and Game Commission. File prefixes are as follows:
* Dam site: Norfolk_DAM-YYYY.xlsx
* Bridge site: Norfolk_62BRG-YYYY.xlsx

It should be noted that a google search did not return any results for "Norfolk Reservoir Arkansas". The only results returned were for ***Norfork***. To account for this typo, the parser will be called `parse_norfork_data`, but the data files will not be renamed. Data and parser will be matched in [`parsing_task_fxns.R`](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7a_temp_coop_munge/src/parsing_task_fxns.R).

Based on a spot check of  the data in the above-mentioned files, the two additional files labeled as Norfolk in the [`queue`](https://drive.google.com/drive/folders/1jGdWewg7uPaMvUwLMWtvfTEwSyYzHQDi) folder appear to contain the same data (`NorfolkReservoir_hwy62_AR_monthlyTempDO_2016-2020.xlsx` and `NorfolkReservoir_dam_AR_monthlyTempDO_2016-2020`). These two files will be ignored.

Within the ten files of interest, the data appears relatively uniform. The first two excel sheets are typically depth/temperature profiles and aggregated data. The remainder of the sheets in each workbook are formatted in `day-month-year` format (e.g. `6-Aug-2016` or `29-July-2016`) and correspond to individual sampling events. Sampling events include the following data:
* Timestamp - includes date and time, timezone extracted from data is UTC
* Barometer (kPA)
* Dissolved oxygen (mg/L)
* Temperature (C)
* Unit ID
* Depth (ft) - manually calculated and referenced from the surface. This column is often not labeled.

**Comment by lindsayplatt** [comment]
Or is it Norfork 😉

**Comment by padilla410** [comment]
@lindsayplatt I finally searched for the reservoir and see what you're talking about :laughing:   I have amended the issue to address this discrepancy.
