### ISSUE TITLE
Troubleshooting initial pipeline build

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#248]
Using this issue to move an email/Team conversation into the repo. This issue is related to #219 and will be used to track any problems executing the full coop data pipeline through the `scmake("8_viz")` step.

This issue will be closed at the same time as #219 and will be considered closed after a successful run of each of the following steps:
* Get the data (`scmake("6_temp_coop_fetch")`)
* Munge  (`scmake("7a_temp_coop_munge")`)
* Combine  (`scmake("7b_temp_merge")`)
* Plot (`scmake("8_viz")`)

After adding `parse_navico_data.R` I was able to run `scmake("6_temp_coop_fetch")`. Running the second step (`scmake("7a_temp_coop_munge")`) resulted in the following errors:
![image](https://user-images.githubusercontent.com/15007294/145480860-3723faae-5f83-40b9-bce1-42387a18da4f.png)
![image](https://user-images.githubusercontent.com/15007294/145480873-5f3615ef-3451-43e8-ab86-e5c79186d564.png)
![image](https://user-images.githubusercontent.com/15007294/145480878-9d61efd1-3f55-4d7f-8a02-2c982e1ceab9.png)

**Comment by padilla410** [comment]
@jread-usgs email reply (lightly edited to connect links):

Julie, I am cc'ing Lindsay because she ran into a similar situation with the same file. 

You are hitting this error because there are multiple files on google drive in the same folder with the same name ("long_term_ntl.csv") and there is a check in scipiper for this condition that throws an error (see [Scipiper PR 100](https://github.com/USGS-R/scipiper/pull/100)). Lindsay and I discussed this a bit ago when she ran into it but we kind of brushed it off as a weird mystery that we worked past by deleting the second file copy of the file on google drive. But you've created several versions of this file on drive and it is the same file Lindsay had issue with, so there is something up (see below)!

![image](https://user-images.githubusercontent.com/15007294/145481750-58cdc31c-bbc3-45a2-aed2-d7835fbabe47.png)


After some digging, it is clear that there is a funky pipeline thing going on, and the issue exists because there is an automated download target that plops the downloaded file into the directory that we're only wanting to use for manually added files (the `in` directories are for manually uploaded files). I didn't realize this was happening, but this target downloads a file and then uploads it to google drive. Unfortunately, it doesn't use our normal function for doing this (`gd_put()`) which includes checks for duplicates and instead pushes it with a googledrive pkg function (see here). Bummer! Because it doesn't use gd_put(), it will create a new file on gdrive every time someone builds that target. 

I've added this issue to our brittle parsers mega-issue #231, but please ignore that issue for now since you should be clear to rebuild your targets now that I've deleted the duplicate files on gdrive. You will need to build `6_temp_coop_fetch/out/coop_all_files.rds.ind` again and do that by changing the dummy_date arg. 

Let me know if you have any issues. This was a funky one to sleuth down, and I'm glad you shared it otherwise Lindsay and I would've thought this was a one-and-done mystery. 

Hope this helps!

**Comment by padilla410** [comment]
@lindsayplatt email:

Oh, wow! Excellent sleuthing and documenting all-around. I looked at that target with git-blame and it looks like it was last changed 3 years ago. I wonder if that was around the time we were settling on gd_put() but hadn't quite finalized it yet? Nice job finding it! Kind of validating to know it is an actual bug in the code and not me just going around duplicating files in the in/ folder with no recollection of doing so🙂

**Comment by padilla410** [comment]
@jread-usgs email:

I think it was code that was in a prior repo (since retired) in support of this paper: https://arxiv.org/abs/1710.11431

and it was copied into this repo. And yes, I think it was a carryover of some prior patterns that we didn't yet understand the drawbacks of.

**Comment by jread-usgs** [comment]
addressed in #249
