### ISSUE TITLE
GCM pipeline - hard-code in subset of lakes for now

### ISSUE THREAD

**Issue by hcorson-dosch** [USGS-R/lake-temperature-model-prep#254]
In setting up our GLM workflow I realized that the subset of 5 lakes we were [randomly selecting](https://github.com/USGS-R/lake-temperature-model-prep/blob/gcm_driver_data_munge_pipeline/7_drivers_munge/src/GCM_driver_utils.R#L85-L93) are not lakes that we can model with GLM. In order to keep moving forward with the GLM work, I did a quick filter of [`lake_centroids_sf_rds`](https://github.com/USGS-R/lake-temperature-model-prep/blob/gcm_driver_data_munge_pipeline/_targets.R#L48) to the site_ids in [`7_config_merge/out/nml_list.rds`](https://github.com/USGS-R/lake-temperature-model-prep/blob/gcm_driver_data_munge_pipeline/7_config_merge.yml#L91) before randomly subsetting to 5 lakes in order to define the `query_cell_centroids_sf`, and ended up with these 5 lake ids:
```r
[1] "nhdhr_77358110"                               "nhdhr_70331671"                              
[3] "nhdhr_{88374465-DA2B-47F8-BFC6-002E7DF1353E}" "nhdhr_70333049"                              
[5] "nhdhr_74924207"  
```
Lindsay and I chatted and agreed that it doesn't make sense to do that filtering in this pipeline, given that we want pull GCM drivers for all lakes, not merely those that we can  model with GLM. So I am instead going to filter the [`lake_cell_xwalk`](https://github.com/USGS-R/lake-temperature-model-prep/blob/gcm_driver_data_munge_pipeline/_targets.R#L64) to the set of lake_ids in `7_config_merge/out/nml_list.rds` in `lake-temperature-process-models` when I define the [`set of lakes`](https://github.com/hcorson-dosch/lake-temperature-process-models/blob/targets_glm_setup/1_prep.R#L13) for the GLM modeling.

In the meantime, in order to move forward on the netCDF work with a set of lakes that we can then test in `lake-temperature-process-models`, @lindsayplatt is going to hard code in this set of lake_ids within [`subset_lake_centroids`](https://github.com/USGS-R/lake-temperature-model-prep/blob/gcm_driver_data_munge_pipeline/7_drivers_munge/src/GCM_driver_utils.R#L85-L93)

**Comment by lindsayplatt** [comment]
Closing as we did this but then also scaled up to MN now.
