### ISSUE TITLE
Navico data: non-unique relationship between `site_id` and `Navico_ID` in nhdr crosswalk

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#257]
I'm not 100% sure if this is a true issue or not, but it did strike me as odd: there is a non-unique relationship between `Navico_ID` and `site_id` in the `lake-temperature-model-prep > 2_crosswalk_munge > out > navico_nhdhr_xwalk.rds` on google drive.

Here is a length comparison between the two fields:
```r
> navico_xwalk <- readRDS('data/2021-12-06/2_crosswalk_munge_out/navico_nhdhr_xwalk.rds') # update with your local path
> length(unique(navico_xwalk$Navico_ID))
[1] 667
> length(unique(navico_xwalk$site_id))
[1] 658
```

A count summary of all the dups:
```r
> navico_xwalk %>% group_by(site_id) %>% tally() %>% filter(n > 1)
# A tibble: 7 x 2
  site_id                                          n
  <chr>                                        <int>
1 nhdhr_{0BB28A37-D665-4735-A2DA-5C08014F9EEF}     2
2 nhdhr_{d7eeb7a2-c7ce-45bd-b329-7038adea7656}     2
3 nhdhr_132544104                                  3
4 nhdhr_155637149                                  2
5 nhdhr_155638724                                  2
6 nhdhr_155641743                                  2
7 nhdhr_155642288                                  3
```

A detailed look at one of the duplicates:
```r
> navico_xwalk %>% filter(site_id == "nhdhr_132544104") %>% select(site_id, Navico_ID, WaterbodyName, State, County)
# A tibble: 3 x 5
  site_id         Navico_ID      WaterbodyName    State County          
  <chr>           <chr>          <chr>            <chr> <chr>           
1 nhdhr_132544104 Navico_1226897 Lower Gar Lake   Iowa  Dickinson County
2 nhdhr_132544104 Navico_1226898 Minnewashta Lake Iowa  Dickinson County
3 nhdhr_132544104 Navico_1253574 Upper Gar Lake   Iowa  Dickinson County
```

Based on a quick view of the area on google maps, it looks like this is a spatial resolution issue: Upper Gar Lake, Minnewashta Lake, and Lower Gar Lake are part of a chain of lakes:
![image](https://user-images.githubusercontent.com/15007294/146059568-885c711b-108f-4149-87ff-f7abd1196b90.png)

**Comment by jread-usgs** [comment]
Yes, I think this is expected. Most of our crosswalks have some kind of deviation from the normal 1:1 NHD-lake:crosswalked-lake relationship. 

Reason being, some versions of lakes are split in certain ways but are merged in the other dataset, like your resolution issue above. This is especially common in the MN lake ids (the "MNDOW" identifiers).

**Comment by jread-usgs** [comment]
Labeled as "wontfix" and closing. This issue will remain and be searchable as a closed issue but we don't intend to take action on it.
