### ISSUE TITLE
Navico data: expand `navico_nhdhr_xwalk.rds` crosswalk

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#259]
The existing crosswalk for mapping the `Navico_ID` field in the Navico temperature data set to `site_id` in `navico_nhdhr_xwalk.rds` is incomplete.

The current raw  temperature dataset (`Waterbody_Temperatures_by_State.rds`) has 2,786 unique entries:
```r
> # unique `Navico_ID` in raw data
> length(unique(navico_raw$Navico_ID))
[1] 2786

> # unique `site_id` in crosswalk
> length(unique(navico_xwalk$site_id))
[1] 658
```

Only 10% of the unique waterbodies in the raw dataset have matching values in the crosswalk:
```r
> # join the raw Navico data to the cross walk and count unique `Navico_ID`
> left_join(navico_raw, navico_xwalk) %>% 
+   filter(!is.na(site_id)) %>% 
+   pull(Navico_ID) %>% 
+   unique() %>% 
+   length() 
Joining, by = "Navico_ID"
[1] 296
```

Finally, while working through this issue I also discovered that there is a non-unique relationship between `Navico_ID` and `site_id` in `navico_nhdhr_xwalk.rds`. This issue is fully documented in #257, but here is a snippet of what is happening:
```r
> # join the raw Navico data to the cross walk and count unique `site_id`
> left_join(navico_raw, navico_xwalk) %>% 
+   filter(!is.na(site_id)) %>% 
+   pull(site_id) %>% 
+   unique() %>% 
+   length()
Joining, by = "Navico_ID"
[1] 294

> # identify non-unique `site_id`s
> left_join(navico_raw, navico_xwalk) %>% 
+   filter(!is.na(site_id)) %>% 
+   group_by(site_id, Navico_ID) %>% 
+   tally() %>% 
+   group_by(site_id) %>% 
+   tally() %>% 
+   filter(n > 1)
Joining, by = "Navico_ID"
# A tibble: 2 x 2
  site_id             n
  <chr>           <int>
1 nhdhr_155637149     2
2 nhdhr_155641743     2
```

**Comment by padilla410** [comment]
I think it depends on your definition of "the same lake" that you've been using for the model. 

I looked at this two ways:

- First, I went back to the raw Navico dataset (`Waterbody_Temperatures_by_State.xlsx`) because it has the lat/long info that I could use to help verify uniqueness. I did a quick summary and found 2,786 unique combinations of `MapWaterbodyId`, `WaterbodyLat`, `WaterbodyLon` which is what I expected to find based on the number of unique `Navico_ID`s in #259. As an FYI, we used the `MapWaterbodyId` field to create the `Navico_ID` field.
 
- Second, I spot checked the duplicates that I identified in `site_id`. One screen shot is included in #257 (for `site_id == "nhdhr_132544104"`) and one for `site_id == nhdhr_155637149` (google maps screenshot pasted below). So a layperson would probably say these are two lakes, but hydrologically they probably aren't (right?)


![image](https://user-images.githubusercontent.com/15007294/146075224-d1cf987c-3c2f-4aa1-9996-db9073e3bde6.png)

**Comment by jread-usgs** [comment]
and one last question - is "navico_raw" a superset of "navico_xwalk"? I.e., if we shift the crosswalk original data to the Water Temperature file, will it also include all of the lakes that have Navico depths, or would we lose some and need to merge the two?

**Comment by hcorson-dosch** [comment]
Sorry - I was delayed in getting to this, but looks like you got it all sorted!
