### ISSUE TITLE
Multiple cooperator datasets not present in `all_coop_dat_linked.feather` due to missing crosswalks

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#267]
Related to PR #218 

Bull Shoals data is not present in `all_coop_dat_linked.feather`. To review the data run the following code snippet:

```r
library(arrow)
library(dplyr)
library(scipiper)

all_coop_dat <- arrow::read_feather(sc_retrieve('7b_temp_merge/out/temp_data_with_sources.feather.ind'))

dat_check <-all_coop_dat %>% 
  dplyr::filter(str_detect(source, "Bull_Shoals"))
```

This issue is likely because the `nhdhr` id was assigned manually in the [parser](https://github.com/USGS-R/lake-temperature-model-prep/blob/0c037ddce5bdab7a7eb3a6ad07c0837972bddcd1/7a_temp_coop_munge/src/data_parsers/parse_missouri_files.R#L34).

While assigning the parser manually when a data set has only one `nhdhr` id seems reasonable it causes a problem when the pipeline calls [`crosswalk_coop_dat`](https://github.com/padilla410/lake-temperature-model-prep/blob/4352b51842201e88e599b18b69d6582fbd7e9a65/7a_temp_coop_munge.yml#L58). The Bull Shoals data is present until the last step in the function: the filtering of [`site_id`](https://github.com/padilla410/lake-temperature-model-prep/blob/4352b51842201e88e599b18b69d6582fbd7e9a65/7a_temp_coop_munge/src/crosswalk_fxns.R#L93-L94) for non-NA values. The Bull Shoals data is removed at this step because it does not have a `site_id` value, only an `id` value. A crosswalk is needed to match the assigned `id` to a `site_id`.

In diagnosing the above error, I also found several additional datasets that have similar issues (no crosswalk). The following data source files also have 100% of the data missing (from `dat_missing` table created inside [`crosswalk_coop_dat`](https://github.com/padilla410/lake-temperature-model-prep/blob/4352b51842201e88e599b18b69d6582fbd7e9a65/7a_temp_coop_munge/src/crosswalk_fxns.R#L86-L89)):
* ~~`7a_temp_coop_munge/tmp/Bull_Shoals_Lake_DO_and_Temp.rds`~~ _addressed in PR #288_
* `7a_temp_coop_munge/tmp/Indiana_CLP_lakedata_1994_2013.rds` - raw data has lat/longs
* `7a_temp_coop_munge/tmp/Indiana_Glacial_Lakes_WQ_IN_DNR.rds` - no lat/longs in data or `explain` file
* `7a_temp_coop_munge/tmp/SD_Lake_temp_export.rds` - raw data has lat/longs (related to #221)
* ~~all `7a_temp_coop_munge/tmp/Norfolk_62BRG-YYYY.rds` files (5 total) - no lat/longs provided but can be estimated from a map (parser is currently manually assigning `nhdhr` id)~~ _addressed in PR #268_
* ~~all `7a_temp_coop_munge/tmp/Norfolk_DAM-YYYY.rds` files (5 total) - no lat/longs provided but can be estimated from a map (parser is currently manually assigning `nhdhr` id)~~ _addressed in PR #268_

**Comment by padilla410** [comment]
The following data source files also have 100% of the data missing (from `dat_missing` table created inside [`crosswalk_coop_dat`](https://github.com/padilla410/lake-temperature-model-prep/blob/4352b51842201e88e599b18b69d6582fbd7e9a65/7a_temp_coop_munge/src/crosswalk_fxns.R#L86-L89):
* `7a_temp_coop_munge/tmp/Indiana_CLP_lakedata_1994_2013.rds`
* `7a_temp_coop_munge/tmp/Indiana_Glacial_Lakes_WQ_IN_DNR.rds`
* `7a_temp_coop_munge/tmp/SD_Lake_temp_export.rds`

**Comment by padilla410** [comment]
Adding in each one of these crosswalks is going to require adding a corresponding argument and additional code into [`crosswalk_coop_dat`](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7a_temp_coop_munge/src/crosswalk_fxns.R). Should we consider refactoring this function?

**Comment by lindsayplatt** [comment]
Hmmm wow, I just have assumed that no crosswalk was needed for these single lake datasets if you provided the NHD id. As it stands, this function must get changed _every time_ we add a new dataset so I think refactoring would make the most sense. I think we should use the argument `id_crosswalk` to pass in a crosswalk for these one-off lakes (it is strange to me that the [generic `id_crosswalk` argument is being passed the `micorps` id crosswalk](https://github.com/USGS-R/lake-temperature-model-prep/blob/0c037ddce5bdab7a7eb3a6ad07c0837972bddcd1/7a_temp_coop_munge.yml#L61)) _or_ edit so that uses the `id` column differently (see instructions about the columns in [the README here](https://docs.google.com/document/d/1Z1fg8ng9IWHS9oiQTxsDvpGBlbgz2bMZ5rWNxfRiHC8/edit#)).

It would be great for @jread-usgs to weigh in when he returns

**Comment by padilla410** [comment]
Side note - there is significant overlap in lakes with data between all MO data that I'm working on right now: Bull Shoals, Univ MO (#269) and MO USACE (#270)

**Comment by padilla410** [comment]
[Updates on the status of the SD crosswalk](https://github.com/USGS-R/lake-temperature-model-prep/issues/221#issuecomment-1091820095)

**Comment by padilla410** [comment]
## Updates on the Status of the SD Crosswalk

One more follow-up here. I started running this issue down this morning. Here's the long and short of it:
* There is a mismatch in lake ID naming conventions between the source of the temperature data ([SD_Lake_temp_export.xlsx](https://docs.google.com/spreadsheets/d/102863Z9-JJMCPqWefQZso_RV3e0lxWBw/edit?usp=sharing&ouid=116457714585704804833&rtpof=true&sd=true)) and the spatial data (`SD_ManagedFisheries.zip` and `South Dakota.zip` in `1_crosswalk_fetch/in`). Here's a peek at what the differences look like:
 
![image](https://user-images.githubusercontent.com/15007294/162223282-7416d946-354c-4340-baeb-87e3ce8392b4.png)

![image](https://user-images.githubusercontent.com/15007294/162223349-60c1eeee-f88d-4695-92a6-c7a8942d414a.png)

* This ultimately means that I will need to find a different data source for crosswalking the SD temp data with NHDHR. The good news, is that I have potentially found [one](https://apps.sd.gov/NR92WQMAP/#)

* I was able to confirm much of this with Jordan this morning (he was the last person to touch many of the SD crosswalk files in January 2022)
* Based on the above info, I would like to close this issue because it is now moot - the spatial info discussed above is no longer relevant to crosswalking the SD temperature data.

@lindsayplatt, I intend to close this issue once I see a 👍 from you. Also, please let me know if you think I'm missing something and should keep this issue open.

As an aside, `SD_ManagedFisheries.zip` and `South Dakota.zip`are the same files.

UPDATE - It is no longer clear to me that we can resolve the crosswalk for this dataset without reaching out to a cooperator in SD. I have spent a good chunk of time poking around the [SD WQ Mapper](https://apps.sd.gov/NR92WQMAP/#UsingTheMap) - it's a pretty nice map, but frustratingly, there is not a great way to do a bulk export of the spatial info. The "Lakes" layer in this mapping tool _does_ contain the "Assessment Unit ID" field that would match to our temperature data:
![image](https://user-images.githubusercontent.com/15007294/162231682-b2b375b4-862b-4f34-90a1-e85f59d1e145.png)

![image](https://user-images.githubusercontent.com/15007294/162231968-5f354f60-f4b8-4f11-98de-543843450762.png)

I have also tried accessing data via the the [SD DANR website] (https://danr.sd.gov/) and via their [spatial data portal](https://opendata2017-09-18t192802468z-sdbit.opendata.arcgis.com/maps/052112ac4fce4489a55c7da9aa9a702c/about) none of these sources provide waterbody data that includes the appropriate "Assessment Unit ID" field.

The heart of the issue is that different agencies within the state use different ID systems for waterbodies.

**Comment by padilla410** [comment]
## Updates on the Status of the Indiana Crosswalks
 I was able to extract and reformat lat/longs from `7a_temp_coop_munge/tmp/Indiana_CLP_lakedata_1994_2013.rds` and derive lat/longs for 446 out of 541 unique `Lake_ID`s

`7a_temp_coop_munge/tmp/Indiana_Glacial_Lakes_WQ_IN_DNR.rds` is a slightly more challenging story - there is no spatial data nor is there any kind of `Lake_ID` numeric system. The munged data set uses a combination of lake name and county name as an id. Using this info, I can match 44 combinations of Lake Name and County to the `Indiana_CLP_lakedata_1994_2013_latlong.csv` data set (out of 139 in the raw data). 

For both of these data sets, I will need to do some updating to the original parsers and troubleshoot as I go.
