### ISSUE TITLE
Resolve duplicate unit conversions

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#272]
Related to closed issue #235. When double checking files after merging PR #268 I noticed that Sam added a [`parse_unit_functions`](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7a_temp_coop_munge/src/data_parsers/parse_unit_functions.R) script to `7a_temp_coop_munge`. This results in a duplicate function

I propose the following steps to resolve this issue:
~1. Move the functions from Sam's script from `7a_temp_coop_munge` to [`generic_utils.R`](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/lib/src/generic_utils.R). Sam's function will replace my conversion function `convert_ft_to_m`~
1. Replace all instances of `convert_ft_to_m` with `feet_to_meters`
2. Double check parsers for opportunities to use `feet_to_meters` and `fahrenheit_to_celsius` (especially, in [`parse_Bull_Shoals_Lake_DO_and_Temp`](https://github.com/USGS-R/lake-temperature-model-prep/blob/2495e066d3bfbb31855a983d690002eb14e8cd56/7a_temp_coop_munge/src/data_parsers/parse_missouri_files.R#L42) - left over from #235).
3. Move `fahrenheit_to_celsius` to [`generic_utils.R`](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/lib/src/generic_utils.R)
4. Remove `parse_unit_functions.R` from `7a_temp_munge/src/data_parsers`

**Comment by padilla410** [comment]
Assuming there are no major bugs hiding, this will take <<30 min.

**Comment by jread-usgs** [comment]
Good catch. That [`feet_to_meters`](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7a_temp_coop_munge/src/data_parsers/parse_unit_functions.R#L3) function is going to be slightly different since it rounds the conversion to get 3.28 instead of the equivalent 3.28084. 

I prefer your function because it is more accurate but that complicates things when replacing it.

**Comment by padilla410** [comment]
It does, but `convert_ft_to_m` is pretty old (2018). I think making all parsers use `feet_to_meters` will add an hour, tops (there are only 20  files in `src/data_parsers` and I can check through the initial commit to quickly ID most of files. I will update the issue
