### ISSUE TITLE
Verify that Vermillion data set has a constant depth of 8 ft

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#277]
Two issues were identified in resolving unit conversion inconsistencies in data parsers. Two parsers need a secondary review to ensure that they have constant depths (as defined in their parsers):
* [`parse_URL_Temp_Logger_2006_to_2017`](https://github.com/USGS-R/lake-temperature-model-prep/blob/2495e066d3bfbb31855a983d690002eb14e8cd56/7a_temp_coop_munge/src/data_parsers/parse_mndow_coop_files.R#L41-L61)
* [`parse_Lake_Vermilion_2016`](https://github.com/USGS-R/lake-temperature-model-prep/blob/2495e066d3bfbb31855a983d690002eb14e8cd56/7a_temp_coop_munge/src/data_parsers/parse_vermillion_files.R#L52-L72)

Comments from PR #274:

the "8ft" must be in the explainer for this, but it seems odd to see this magic number in here without a comment. Again, this isn't a change your PR needs to make.

_Originally posted by @jread-usgs in https://github.com/USGS-R/lake-temperature-model-prep/pull/274#discussion_r781224662_

Since I don't see a comment in the function, just verifying here that this dataset only has data at 11ft depth?

_Originally posted by @jread-usgs in https://github.com/USGS-R/lake-temperature-model-prep/pull/274#discussion_r781222341_

A fully resolved issue would involve adding a clarifying comment into the relevant parsers.

**Comment by padilla410** [comment]
Hey @limnoliver, I just wanted to ping you on this issue before I resolve it. There are two sets of data parsers where the depth field is manually set:
*  In `parse_vermillion_files` ([example](https://github.com/USGS-R/lake-temperature-model-prep/blob/73348f91d54b2fe4c568cfba10ad8b3b29613c25/7a_temp_coop_munge/src/data_parsers/parse_vermillion_files.R#L63)) the following files have some sort of manual depth setting:
   * Set to 0 ft depth: 
      * Joes_Dock_2013
      * Joes_Dock_Logger_2012
    * Set to 8 ft depth:  
      * Lake_Vermilion_2016
      * Logger_Temps_2009_Joes_Dock
      * Logger_Temps_2009_Open_Water
      * Logger_Temps_2010_Open_Water
      * Logger_Temps_2011_Open_Water
      * Open_Water_Logger_2013
      * Temp_Logger_Data_2015
      * Vermilion_Logger_2014
* In `parse_mndow_coop_files`  - [`parse_URL_Temp_Logger_2006_to_2007`](https://github.com/USGS-R/lake-temperature-model-prep/blob/73348f91d54b2fe4c568cfba10ad8b3b29613c25/7a_temp_coop_munge/src/data_parsers/parse_mndow_coop_files.R#L52) has depth set to 11 ft

I took a look at all of the files listed above and the hardcoded depths seem reasonable (i.e., raw data didn't come with a depth field). Is there an old email floating around somewhere that documents the hardcoded depths? I would like to add a comment to the parser reflecting this, if possible.

**Comment by limnoliver** [comment]
Hi Julie-

Found a quick answer for the `URL_Temp` data, which is that the cooperator provided the depth in the [explainer file](https://docs.google.com/document/d/18BMvLy-Rx321u_rwyrm-NJYV82cvP6eHUbjLXOvNSGQ/edit). 

Will do some more poking for Vermillion...

**Comment by limnoliver** [comment]
Looks like the Vermillion munge predates me (e.g., bulk add of parser files [here](https://github.com/USGS-R/lake-temperature-model-prep/commit/814ab724831190abf9d5b069d7a2ffa9bc8b1db7)). My best guess is that @jread-usgs might have the email that is referenced [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/73348f91d54b2fe4c568cfba10ad8b3b29613c25/7a_temp_coop_munge/src/data_parsers/parse_vermillion_files.R#L50-L51). Saying that because it looks like a lot of [though/investigation went into Vermillion](https://docs.google.com/presentation/d/1IuV-0bDdWcqwtgwXRbbeJRMAi7A1DZr1/edit) specifically.

**Comment by padilla410** [comment]
Thanks for the quick turn around, @limnoliver -- really appreciate it! I'll follow up with @jread-usgs.

**Comment by jread-usgs** [comment]
Looks like those did indeed predate Sam's creation of the coop parser parts of the pipeline. The files were from a prior repo that aided earlier versions of this work: https://github.com/USGS-R/pgml_temperature_prediction/tree/master/1_all_raw_data/in

Those parsers came from [here](https://github.com/USGS-R/pgml_temperature_prediction/blob/1361354094d0b13f49499d673840fd1a8029164d/1_data_s3_assimilate/src/parse_vermillion_files.R) and we may need to check with David too (I am seeing if I can track down the email in question)

**Comment by padilla410** [comment]
Jordan was able to track down a 2018 email on the Vermilion data. I have added an additional [`explainer`](https://docs.google.com/document/d/1mS3tROmCmVVhndJitJWH3BiJwk7Va23vNUjo-FVOyA0/edit?usp=sharing) file documenting it.

I will close this issue when I add a PR with a few comment updates after wrapping up the Univ of MO data this morning.

Thanks all for running down these files.

**Comment by padilla410** [comment]
I am closing this issue. It looks like the depth of "8 ft" was provided in an email. As I mentioned earlier in the thread, I added an "explainer" file to the shared google drive.
