### ISSUE TITLE
Running down missing Iowa DNR spatial data

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#286]
Raw Iowa DNR data has 176 lakes. When I run `scmake("7a_temp_coop_munge")` only 113 of these lakes make it into `all_coop_dat_linked.feather`. There are two reasons for this:
1. Some lakes are dropped early in the pipeline because they do no have spatial data available in [`1_crosswalk_fetch/in/Iowa_Lake_Locations.csv`](https://drive.google.com/file/d/1k1U65PtXpb2X-blbPKBFJGbfG_tzbOjf/view?usp=sharing) so it never gets compared to NHDHR data
2. Other lakes are dropped because they do not have matches in NHDHR (this is the expected and desired behavior)

The IADNR data set is a pretty good one so it might be worth running down the extra spatial data. Here are the lakes without spatial data:
```r
Browse[2]> print(summ_ia_nonhd, n = 50)
# A tibble: 45 x 7
   state_id no_of_sample_days year_min year_max `Lake Name` `UTM (NAD83)_E`
   <chr>                <int>    <dbl>    <dbl> <chr>                 <dbl>
 1 Iowa_49                 54     2000     2020 NA                       NA
 2 Iowa_100                48     2000     2016 NA                       NA
 3 Iowa_104                48     2000     2016 NA                       NA
 4 Iowa_118                48     2000     2016 NA                       NA
 5 Iowa_23                 48     2000     2016 NA                       NA
 6 Iowa_106                43     2000     2016 NA                       NA
 7 Iowa_117                41     2000     2016 NA                       NA
 8 Iowa_26                 23     2000     2007 NA                       NA
 9 Iowa_269                20     2006     2016 NA                       NA
10 Iowa_235                 7     2006     2007 NA                       NA
11 Iowa_207                 6     2006     2007 NA                       NA
12 Iowa_208                 6     2006     2007 NA                       NA
13 Iowa_209                 6     2006     2007 NA                       NA
14 Iowa_210                 6     2006     2007 NA                       NA
15 Iowa_211                 6     2006     2007 NA                       NA
16 Iowa_218                 6     2006     2007 NA                       NA
17 Iowa_220                 6     2006     2007 NA                       NA
18 Iowa_222                 6     2006     2007 NA                       NA
19 Iowa_227                 6     2006     2007 NA                       NA
20 Iowa_228                 6     2006     2007 NA                       NA
21 Iowa_229                 6     2006     2007 NA                       NA
22 Iowa_233                 6     2006     2007 NA                       NA
23 Iowa_234                 6     2006     2007 NA                       NA
24 Iowa_238                 6     2006     2007 NA                       NA
25 Iowa_242                 6     2006     2007 NA                       NA
26 Iowa_244                 6     2006     2007 NA                       NA
27 Iowa_249                 6     2006     2007 NA                       NA
28 Iowa_253                 6     2006     2007 NA                       NA
29 Iowa_255                 6     2006     2007 NA                       NA
30 Iowa_258                 6     2006     2007 NA                       NA
31 Iowa_262                 6     2006     2007 NA                       NA
32 Iowa_265                 6     2006     2007 NA                       NA
33 Iowa_266                 6     2006     2007 NA                       NA
34 Iowa_268                 6     2006     2007 NA                       NA
35 Iowa_270                 6     2006     2007 NA                       NA
36 Iowa_219                 5     2006     2007 NA                       NA
37 Iowa_225                 5     2006     2007 NA                       NA
38 Iowa_246                 5     2006     2007 NA                       NA
39 Iowa_226                 4     2006     2007 NA                       NA
40 Iowa_213                 1     2006     2006 NA                       NA
41 Iowa_239                 1     2006     2006 NA                       NA
42 Iowa_243                 1     2006     2006 NA                       NA
43 Iowa_250                 1     2006     2006 NA                       NA
44 Iowa_263                 1     2006     2006 NA                       NA
45 Iowa_267                 1     2006     2006 NA                       NA
```

Currently, generating this summary is a bit tricky. If you wanted to reproduce it you would do the following:
1. add `browser()`  right before `warning` in `crosswalk_coop_dat()` in [`crosswalk_fxns.R`](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7a_temp_coop_munge/src/crosswalk_fxns.R). the `browser()` function will stop `crosswalk_coop_dat()` before it drops all lakes that are missing a `site_id`.
2. Run `scmake('7a_temp_coop_munge')`
3. When the run stops use the following script to generate the summary:

```r
# Load IA DNR data from `dat_all_linked`
dat_iadnr <- dat_all_linked %>% 
  filter(source == '7a_temp_coop_munge/tmp/Iowa_DNR_LimnoProfiles_2000_2020.rds')

# Filter IA DNR for lakes with no NHDID
# note - this may include lakes that do have spatial data
# but do not have matches in NHDID
dat_ia_nonhd <- dat_iadnr %>% 
  filter(is.na(site_id))

# Create a summary that counts the number of unique sampling days
summ_ia_nonhd <- dat_ia_nonhd %>% 
  group_by(state_id) %>% 
  summarise(no_of_sample_days = length(unique(DateTime)),
            year_min = min(lubridate::year(DateTime)),
            year_max = max(lubridate::year(DateTime)))

# load the IA crosswalk
ia_xwalk <- read_csv('1_crosswalk_fetch/in/Iowa_Lake_Locations.csv')
ia_xwalk$state_id <- paste('Iowa_', ia_xwalk$LakeID, sep = '')
ia_xwalk <- ia_xwalk %>% 
  dplyr::select(state_id, `Lake Name`, `UTM (NAD83)_E`, `UTM (NAD83)_N`)

# Join the IA crosswalk to the No NHDID summary and filter
# for sites without spatial data
summ_ia_nonhd <- dplyr::left_join(summ_ia_nonhd, ia_xwalk) %>% 
  filter(is.na(`Lake Name`)) %>% 
  arrange(desc(no_of_sample_days))
```

**Comment by padilla410** [comment]
@padilla410 check online resources before reaching out to cooperators. Check this website: https://github.com/USGS-R/lake-temperature-model-prep/issues/286

**Comment by padilla410** [comment]
I took a detailed look at two Iowa related lookup tables we have in `2_crosswalk_munge/out` and then I joined them together:\

```r
library(scipiper)
library(dplyr)

iowa <- readRDS(sc_retrieve('2_crosswalk_munge/out/Iowa_nhdhr_xwalk.rds.ind'))
iadnr <- readRDS(sc_retrieve('2_crosswalk_munge/out/iadnr_nhdhr_xwalk.rds.ind'))

ia_comb <- dplyr::left_join(iadnr, iowa)
```

The output:
```r
> head(ia_comb, 5)
# A tibble: 5 x 7
  IADNR_ID    site_id                                      Iowa_ID `Lake Name`  County Zone  `STORET ID`
  <chr>       <chr>                                        <chr>   <chr>        <chr>  <chr> <chr>      
1 iadnr_AHQ91 nhdhr_133534596                              Iowa_51 Lake Ahquabi WARREN 15T   22910002   
2 iadnr_ALL68 nhdhr_146615721                              NA      NA           NA     NA    NA         
3 iadnr_ANI15 nhdhr_153930921                              Iowa_52 Lake Anita   CASS   15T   22150002   
4 iadnr_AQ215 nhdhr_{1CE08429-D086-4364-8EBB-8DBB339EFC38} NA      NA           NA     NA    NA         
5 iadnr_AQ315 nhdhr_{D5F1D78B-DBAF-454E-A59F-E2C1CD76EE23} NA      NA           NA     NA    NA 
```

It looks to me that the State of Iowa has two ID systems for lakes: one system listed under the `Iowa_ID` field and another listed under the `IADNR_ID` field. The `Iowa_ID` field  is a modified version of a field called `LakeID` provided in the raw data. The `LakeID` field in the raw data is 1-3 digits long (e.g., `001` or `1`, depending on the raw data set). It is used by the temperature data sets added PR #284 and in PR #211. The `IADNR_ID` field is a 5 character combination of letters and numbers (e.g., `AHQ91` or `AQ215`). It looks like it comes from a body of work aimed at [adding IA bathy data](https://github.com/USGS-R/lake-temperature-model-prep/commit/f3ff7f1d700c5aff6305f723d7bb462ed926a991) to the pipeline. There does not appear to be a relationship between the two Iowa lake reference systems (see the first row of the table - Lake Ahquabi).

The [link](https://www.iowadnr.gov/idnr/Fishing/Where-to-Fish/Lakes-Ponds-Reservoirs/LakeDetails?lakeCode=BHA81) that Gretchen provided in our meeting on 1/21/2022 uses the `IADNR_ID` system, but the missing lakes above use the `Iowa_ID` system. I have not found an Iowa website that provides the `LakeID`. Since the two systems don't seem to intuitively relate to each other, I have not been able to find the `LakeID`s for the 45 lakes listed above.

**Comment by padilla410** [comment]
@jread-usgs do you know of any smart way to try and combine the two crosswalks? Thoughts?

**Comment by jread-usgs** [comment]
I think I might need some help with the basis of the question. Is there a reason that we need to combine them? 
A lot of the states have multiple ID systems for the same lakes - such as in Wisconsin, the State DNR uses WBICs, but the Long-Term Ecological Research program uses two letter IDs. I've kept these separate as different IDs in the past.

**Comment by padilla410** [comment]
I thought there might be a way to compare the two datasets against each other to see if we could pick up a few more IDs. Otherwise, we will need to reach out to the original data provider.

**Comment by jread-usgs** [comment]
ahh. 

Yeah, this is the super frustrating case where we have non-unique ways of matching to lakes, such as name and county. 

I bet with the combination of name, county, _and_ lat/lon, we could go through some targeted manual effort to find the NHDHR for the lakes with significant data

![image](https://user-images.githubusercontent.com/2349007/150875517-822a006a-8bb7-41b8-88b0-062350efd953.png)

The GNISName xwalk, plus the county xwalk, and probably some GUI-based GIS work could perhaps help us with this if we want to do some data rescue 🥼

**Comment by jread-usgs** [comment]
Another slice of sluething is that the STORET ID could provide us value, because the ID seems to be embedded in the water quality portal's site ID:

```r
readRDS('2_crosswalk_munge/out/Iowa_nhdhr_xwalk.rds')
# A tibble: 114 × 6
   site_id         Iowa_ID `Lake Name`       County        Zone  `STORET ID`
   <chr>           <chr>   <chr>             <chr>         <chr> <chr>      
 1 nhdhr_137044605 Iowa_2  Arrowhead Lake    SAC           15T   22810001   
 2 nhdhr_74255396  Iowa_3  Arrowhead Pond    POTTAWATTAMIE 15T   22780002   
 3 nhdhr_133529131 Iowa_5  Badger Creek Lake MADISON       15T   22610004   
 4 nhdhr_137027971 Iowa_6  Badger Lake       WEBSTER       15T   22940001   
 5 nhdhr_152753949 Iowa_8  Beeds Lake        FRANKLIN      15T   22350001   
 6 nhdhr_137028774 Iowa_9  Big Creek Lake    POLK          15T   22770004   
 7 nhdhr_132543137 Iowa_10 Big Spirit Lake   DICKINSON     15T   22300014   
 8 nhdhr_137044669 Iowa_11 Black Hawk Lake   SAC           15T   22810002   
 9 nhdhr_147258864 Iowa_13 Bob White Lake    WAYNE         15T   22930001   
10 nhdhr_152139787 Iowa_14 Briggs Woods Lake HAMILTON      15T   22400004   
# … with 104 more rows
readRDS('2_crosswalk_munge/out/wqptemp_nhdhr_xwalk.rds') %>% filter(site_id == 'nhdhr_137044605')
          site_id MonitoringLocationIdentifier OrganizationIdentifier resultCount
1 nhdhr_137044605              21IOWA-22810001                 21IOWA          13
2 nhdhr_137044605          21IOWA_WQX-22810001             21IOWA_WQX          58
```

**Comment by jread-usgs** [comment]
Nevermind, this isn't helpful because I misunderstood the comment about missing spatial information for the lakes

> Some lakes are dropped early in the pipeline because they do no have spatial data available in 1_crosswalk_fetch/in/Iowa_Lake_Locations.csv

I thought that meant the lat/lon was empty, but those lake IDs aren't in that file (no info exists). Carry on :)

**Comment by jread-usgs** [comment]
This isn't helpful for _this_ set of Iowa lake IDs, but when poking around trying to see what I could find, it became clear that our _other_ Iowa lake IDs (the DNR ones) are very truncated. 

online there are 1,535 rows/lakes (see image from [geodata.iowa](https://geodata.iowa.gov/datasets/iowadnr::lake-management/explore)), and our crosswalk only has 133, since it is built by only lakes that have contours. 
![image](https://user-images.githubusercontent.com/2349007/151256583-f4c88e74-d6d3-488e-a1c0-587623fa66e7.png)

**Comment by jread-usgs** [comment]
And joy. There is a _third_ set of IOWA DNR ids, which is used in the [Major Water Sources in Iowa](https://www.arcgis.com/home/item.html?id=1e8edbf6fd1c498ea21df66bb9e26f8f) (which has a lakes layer). IDs take the form of "IA 04-UDM-0275-L" and I don't see a relationship with the other two sources of IDs we've seen so far. 

The 1,535 lakes above does have `UTMEasting` and `UTMNorthing` fields, plus that `id` shown above in the screenshot.

**Comment by padilla410** [comment]
Draft cooperator email sent to Lindsay Platt on 2022-03-02

**Comment by lindsayplatt** [comment]
Email sent out to Dr. Wilkinson on 2022-03-02.

**Comment by lindsayplatt** [comment]
Uh oh, got an email kickback for failed delivery. @jread-usgs is Grace now at Wisconsin? Can you point us to the correct contact info if you know it?

**Comment by padilla410** [comment]
Grace Wilkinson as kind enough to run manually down our top 9 reservoirs of interest. I am going to update the Iowa crosswalk and get these lakes into the pipeline. I will close this issue once I complete and verify this update in  a PR. I expect to do this early next week.

**Comment by padilla410** [comment]
Grace Wilkinson ran down several locations. Updates are in the ["explain" file](https://docs.google.com/document/d/1ZXvohYWoDIY29kZ4TDVBbRXG7XVJ1Bsj7JFDxZLx1DE/edit)
