### ISSUE TITLE
MO data loss due to point-in-polygon crosswalk method

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#289]
University of Missouri data (documented in issue #269) comes with a table that includes spatial info for the eight lakes in the data set:
Lake Name | Lake ID Number | County | Lat | Long
-- | -- | -- | -- | --
Bull Shoals Lake | 100 | Ozark | 36.5308 | -92.6047
Lake Ozark - Bagnell Dam | 149 | Miller | 38.2039 | -92.6236
Lake Stockton | 93 | Cedar | 37.6917 | -93.7667
Mark Twain Lake | 145 | Ralls | 39.5223 | -91.6467
Pomme De Terre Lake | 92 | Hickory | 37.9017 | -93.32
Table Rock Lake | 98 | Stone | 36.595 | -93.3108
Truman Res. | 89 | Benton | 38.2639 | -93.4083
Wapapello Lake | 30 | Wayne | 36.9311 | -90.2806

However, after [completing the steps](https://github.com/USGS-R/lake-temperature-model-prep#crosswalk-alternative-id-comes-from-point-based-spatial-data-such-as-monitoring-locations) to link `Lake ID Number` to `NHDHR` only four waterbodies have `NHDHR` matches:

site_id | Missouri_ID | Lake Name | County
 -- | -- | -- | --
nhdhr_120032533 | Missouri_100 | Bull Shoals Lake | Ozark
nhdhr_106716325 | Missouri_93 | Lake Stockton | Cedar
nhdhr_120032180 | Missouri_145 | Mark Twain Lake | Ralls
nhdhr_120031146 | Missouri_89 | Truman Res. | Benton

The missing reservoirs are not small:
* Wapapello - ~3,400 ha
* Pomme De Terre - 3165 ha
* Table Rock - 17,440 ha
* Lake Ozark - ~21900 ha

and therefore are likely in NHDHR, but the spatial info might not align well with NHDHR data.

The count of profiles for each lakes ranges from 12-16 unique sampling events.

**Comment by jread-usgs** [comment]
Quick map of the location for the Bagnell Dam:
![image](https://user-images.githubusercontent.com/2349007/150846994-c0038af6-0281-4230-b6e5-cf91439e8684.png)

So this likely fell outside of the point-in-polygon analysis, which lost the mapping to this reservoir. Probably similar for the others too, I'd guess.
