### ISSUE TITLE
GCM Munging - finalize netCDF format before data release completion

### ISSUE THREAD

**Issue by hcorson-dosch** [USGS-R/lake-temperature-model-prep#291]
In #252, we landed on providing the WGS84 coordinates for the grid cell centroids in the munged GCM netCDF files, in place of the projected coordinates (see #281). At the moment, we're also including the original GCM grid crs information and grid parameters in the global attributes of those netCDF files:
![image](https://user-images.githubusercontent.com/54007288/151230833-50ecd7bf-1c90-4997-9f8b-54ff95da16c8.png)

Before we complete the data release, we'll want to run this approach by Blodgett, as it may confuse users and make them think the coordinates provided in these netCDF files are in that CRS, rather than WGS84 (see discussion [here](https://github.com/USGS-R/lake-temperature-model-prep/issues/252#issuecomment-1022504277)).

**Comment by hcorson-dosch** [comment]
Here's a view of the latest netCDF, which also shows the attributes for the `lat` and `lon` variables:
![image](https://user-images.githubusercontent.com/54007288/155388906-765e4038-7c8f-422a-96b2-0ec6502f2357.png)

**Comment by hcorson-dosch** [comment]
@dblodgett-usgs I was hoping you could weigh in on this netCDF format for the munged downscaled GCM driver data.

If you recall, you, Lindsay, and David Watkins and I chatted on 1/24 re: what set of spatial coordinates to provide when writing to netCDF using `write_timeseries_dsg()`. I gave a quick overview of my initial approach:
> we have been working with the projected coordinates to reconstruct the grid prior to making our query to GDP. After downloading and munging the data, our plan is to store that data in a netCDF, in DSG format. In my first attempt, I was providing the projected coordinates as lat/long to the write_timeseries_dsg() function, then (since the associated attributes added by that function pertain to decimal degree coordinates, and that format would violate netCDF CF conventions), I was reopening the .nc file returned by write_timeseries_dsg()and renaming those variables to iy and jx , following netCDF CF attribute conventions, and then also providing a grid mapping variable

Per your recommendation, we instead decided to [provide WGS84 longitude and latitude coordinates](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7_drivers_munge/src/GCM_driver_nc_utils.R#L48-L54) to `write_timeseries_dsg()`

As of now, I'm still providing attributes for the native grid projection (crs, cellsize, xmin, ymin, nx, and ny) in the global attributes of the netCDF:
![image](https://user-images.githubusercontent.com/54007288/155399315-7c193b2d-2759-40a9-a060-c70dcf5ef5bd.png)

But I am making in clear in the `long_name` attributes for the `lat` and `lon` variables that the provided coordinates are in WGS84:
![image](https://user-images.githubusercontent.com/54007288/155399473-eccc8c46-4b7c-44da-ab32-7cccf2359d11.png)

**My question for you is - do you think that providing information about that native grid crs in the global attributes either a) violates standard netCDF CF attribute conventions, or b) is likely to confuse users of the dataset and imply these data are in that CRS?**

**Comment by dblodgett-usgs** [comment]
No, non-CF global attributes will not cause problems. 

If I follow, I would rename your `global:crs` attribute to `source_raster_crs` and append `source_raster_` to the other globals that apply to that original raster grid. 

Also consider adding a `global:source` attribute with a brief description that these data were derived from a source raster in the specified coordinate system. If a person wanted to get back to the precise grid coordinates, they could using the provided `source_raster_crs`. 

That make sense? 

(for reference)
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch02s06.html

**Comment by hcorson-dosch** [comment]
Yes, that makes sense and seems like a good solution. Thanks, Dave!
