### ISSUE TITLE
Updating data for rerun of Cannonsville and Pepacton reservoir models

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#295]
We need to update our DRB reservoir (Cannonsville and Pepacton) models through 2021. This requires updates to data in this repository as well as in [delaware-model-prep](https://github.com/USGS-R/delaware-model-prep). In order for Hayley to rerun GLM on these reservoirs, we need to update: 

- [x] [Reservoir temperature observations](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7b_temp_merge.yml#L76) comprised of cooperator data as well as a pull from NWIS. We won't update the cooperator data, but should repull [data from NWIS](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/6_nwis_fetch.yml#L30). [lake team]
- [x] Updated NLDAS driver data through 2021. Last time the files used were NLDAS_time[0.367700]_x[397]_y[136].csv and NLDAS_time[0.367700]_x[401]_y[136].csv [lake team]
- [x] [Observed stream inflows](https://github.com/USGS-R/delaware-model-prep/blob/78e7e9cdb1d00867d5e1265a7e399d4adbfaca35/9_collaborator_data.yml#L306) to the reservoirs. Flows are pulled from a national repository, so we should repull [these data](https://github.com/USGS-R/national-flow-observations). [lake team?]
- [x] [Modeled inflow temperatures](https://github.com/USGS-R/delaware-model-prep/blob/main/9_collaborator_data.yml#L314) to the reservoirs. Temperature is from a [run of PRMS-SNTemp](https://code.usgs.gov/wma/wp/run-prms-sntemp/-/tree/main), and we will need to update this run through 2021. This requires updated GridMET drivers, which Margaux is working on, and should be the latest version of the NHM (v5.2). [forecast team]
- [x] Observed reservoir [water budget data](https://github.com/USGS-R/delaware-model-prep/blob/main/2_observations.yml#L182), which will consist of updating the [NWIS pulls of release/diversion information](https://github.com/USGS-R/delaware-model-prep/blob/main/2_observations.yml#L156). [forecast team]

Lauren and Sam will work on updating the national flow and temperature dataset, as well as the PRMS-SNTemp runs (after Margaux has DRB GridMET in hand). Margaux will begin building a data release for this year's forecasts such that Hayley will be able to point to ScienceBase to grab all required reservoir data to run GLM (similar to last time).

**Comment by lindsayplatt** [comment]
Just to clarify, for `observed stream inflows` and `modeled inflow temperatures`, the actual updating is being completed by you and Lauren? So the steps here are just saying to make sure to use/gather these updated data outputs?

**Comment by limnoliver** [comment]
Yep, I updated the text above to be clearer about which groups will do which pieces. Mostly wanted to put them here because Hayley will need all of these things to rerun GLM.

**Comment by padilla410** [comment]
FYI - @jread-usgs is going to run code necessary to complete the NLDAS update for the Lakes Team. It's a low level of effort process on his machine and it is completed locally because the machine needs to be authenticated to NASA. Further details on _why_ the workflow needs to be done this way are documented in issue #1.

**Comment by jread-usgs** [comment]
For the DRB footprint for NLDAS, this requires updating these two parts of `6_drivers_fetch.yml` to
```yaml
  replete_time_range:
    command: c(t0=I(0), t1 = I(377900))
    
  feature_NLDAS_cells:
    command: cells_all(NLDAS_grid, x_range = I(c(387, 408)), y_range = I(c(107, 144)))
```
and then running `scmake('7_drivers_munge/out/7_drivers_munge_tasks.ind')`
`t1` is the last timestep of NLDAS data we're interested in and the `x_range` and `y_range` are the cell indices of the cube extent we're pulling (sketch available in #1). I found `t1` by going to https://hydro1.gesdisc.eosdis.nasa.gov/dods/NLDAS_FORA0125_H.002

**Comment by jread-usgs** [comment]
[NLDAS_time[0.377900]_x[401]_y[136].csv](https://github.com/USGS-R/lake-temperature-model-prep/files/8081937/NLDAS_time.0.377900._x.401._y.136.csv)
[NLDAS_time[0.377900]_x[397]_y[136].csv](https://github.com/USGS-R/lake-temperature-model-prep/files/8081942/NLDAS_time.0.377900._x.397._y.136.csv)

☝️ these files go to 2022-02-09 @padilla410

**Comment by padilla410** [comment]
@limnoliver Task 5 involves work in [`delaware-model-prep`](https://github.com/USGS-R/delaware-model-prep). I have successfully cloned the repo, but does this use a shared cache like `lake-temperature-model-prep`? Will I have google drive access issues?

**Comment by limnoliver** [comment]
Sorry for not stating that one clearer, you can _just_ do the NWIS repull that's linked in `lake-temp-model-prep`, so no need to interact with the other budget data (and yes, you would have run into access issues).

**Comment by limnoliver** [comment]
I think so! This is making me think, since we are still dependent on flow observations, that we could have you repull the national _flow_ data (instead of temperature as we discussed yesterday). That repo is pretty clean and already on HPC...I'll reach out via chat to discuss.

**Comment by limnoliver** [comment]
Oops, sorry Julie, I thought you were inferring that updating #1 got you to rebuild all the NWIS files, including what was needed for #5. I don't think this is the case; #5 is updating diversion data, and that target is [here](https://github.com/USGS-R/delaware-model-prep/blob/main/2_observations.yml#L156).

**Comment by padilla410** [comment]
Howdy folks, looks like Hayley and I have wrapped up all the tasks under this issue. If I can get a 👍 from @limnoliver I will close this.

**Comment by hcorson-dosch** [comment]
I didn't have any part in all that data gathering work (thank you all for pulling the data together), but I do now have all the data I need for the reservoir models

**Comment by limnoliver** [comment]
Yep, we're good. Let's close it!
