### ISSUE TITLE
restructure 7a_temp_coop_munge to avoid individual builds when cooperator files added

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#31]
Currently, parsed cooperator files are ignored, and only the combined munged data is pushed to google drive. This means that if a new cooperator file is added and someone else (other than the original parser computer) wants to update, all files have to be downloaded and parsed.

Options might be to:

1. Push the individual munged files to google drive
2. Have new files simply added to the old combined file, assuming that all old data are "good" and we are simply missing new files.

**Comment by aappling-usgs** [comment]
How long does it take to download and munge all the files?

**Comment by limnoliver** [comment]
Not too long (~2 hours?). The biggest hurdle seems to be OS-specific issues with accessing .accdb files that trips the process up. So then, a third solution would be to fix that issue, and having local rebuilds wouldn't be too big of an issue.

**Comment by aappling-usgs** [comment]
Hmm, gotchya. Or always run this phase on a computer with the right OS (and ideally also with some cooperator files already processed)?

**Comment by limnoliver** [comment]
Yeah exactly. Currently that's me.

**Comment by limnoliver** [comment]
I think I've come around to the opinion that we should leave this part of the pipeline as-is, but make some changes on the next rebuild to add more defenses against rebuilds and failed rebuilds. These include:

1) Saving access database files in a different format on Google Drive (outside of the repo) so that we don't have to deal with Access-to-R issues that seem to be computer-specific.
2) Sort file names when creating `coop_all_files`
3) Write and indicate a file for `coop_all_files` instead of an R object. Currently, all users have to force rebuild this step.

**Comment by jread-usgs** [comment]
We have a potential task related to this in the document generated to onboard @lindsayplatt 

Is that higher priority and more well-defined now?

**Comment by limnoliver** [comment]
Yes, this is a pretty discrete task now, and guessing it would take me an ~hour. I think it can wait until the next time we're in mucking around in the coop files (e.g., we decide to parse more files) since it will trigger a rebuild.

**Comment by lindsayplatt** [comment]
I believe all 3 of the issues noted in [this comment above](https://github.com/USGS-R/lake-temperature-model-prep/issues/31#issuecomment-574729935) were addressed in #146
