### ISSUE TITLE
Missing getter: `1_crosswalk_fetch/out/mo_usace_sampling_locations_sf.rds`

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-model-prep#345]
`1_crosswalk_fetch/out/mo_usace_sampling_locations_sf.rds` is missing from `getters.yml`

**Comment by padilla410** [comment]
Hey @jread-usgs, I assigned this to myself, but would you consider adding it in as a commit to your current PR? It's a quick fix.

**Comment by jread-usgs** [comment]
Yes, will do
