### ISSUE TITLE
New NHD lakes for IN, IA, SD, and ND

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#35]
This is a spin-off of #33 

We currently fetch the Winslow et al. shapefile and use that to make all of our downstream decisions. I'd like to append to that w/ lakes in other states (and potential lakes in WI, MN, MI that are missing) and either use NHD medium res w/ perm IDs (same as Winslow) or use a different prefix for those lakes to signify a different source. 

I want to make this manageable, so that we aren't just creating a shapefile that has _all_ of the lakes in those states, regardless of whether we'll end up modeling them, but this is a bit of a chicken before the egg issue (i.e., we don't know we won't model them until we know they don't meet the data requirements). 

We get our existing shapefile [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/1_crosswalk_fetch.yml#L32)

There is a geodatabase that the MGLP uses that has their IDs (useful for another crosswalk) and contains all of the potential priority lakes (seems to have ~72K lakes in it). 

From that file:
```r
MGLP <- sf::st_read(dsn = "~/Downloads/MGLP_data&metadata/MGLP_model_data&results.gdb/", layer = 'MGLP_LAKES')
```
| State | Lake Count |
| --- | --- |
| IA | 100 |
| IN | 9924 |
| SD | 4345 |
| ND | 4151 |

Plotting all lakes in these states < 25 acres (3,535 lakes):
```r
plot(filter(MGLP, STATE %in% c("IN", "IA","SD","ND"), ACRES > 25)[,1], col = 'dodgerblue', border = NA)
```

![MGLP subset](https://user-images.githubusercontent.com/2349007/53272234-55074b80-36b6-11e9-94d3-1ef66772df81.png)

**Comment by jread-usgs** [comment]
We want to append to and rebuild `1_crosswalk_fetch/out/lakes_sf.rds`, which later is used to calculate centroids for the driver cells.

**Comment by jread-usgs** [comment]
It looks like NHD medium res is no longer available via their FTP. Options: 1) I have it all locally, and could post on gdrive, 2) get it from NHDPlusv2, 3) pivot away from NHD med res to high res. 

Downside of three is that we'd need to do a med -> high crosswalk for the existing lakes. Upside is that we probably should've used HR in the first place...(but it is more of a data headache to include).

**Comment by jzwart** [comment]
Thinking more long term, the High Res version is going to be updated / improved upon and will have some more bells and whistles such as flow accumulation rasters which would allow for watershed delineation and modeling of water and nutrient loads to lakes not on the stream network. [Here ](https://docs.google.com/document/d/1xApqFykG0nhOcHMQRvBjsOIwbsvfftp9z7yzoPQ7su0/edit#bookmark=id.n5hojcbs1drl)are some notes from a meeting we had a while ago. 
I think the High Res version also allows for easy connection to other tools /products such as [LakeCat](https://www.epa.gov/national-aquatic-resource-surveys/lakecat).

**Comment by jread-usgs** [comment]
I agree w/ @jzwart but I am kind of punting on this right now by using the MGLP's lakes and their identifiers for the new states. I agree we should make a pivot to HR, but a bunch of the new data is already indexed to the MGLP IDs, so we'd need a crosswalk to that either way. The code I have in #38 has a single `sf` set of lakes for all of the downstream operations, so we can replace that w/ a different version and/or different IDs in the future.

**Comment by jread-usgs** [comment]
This is now covered in #53
