### ISSUE TITLE
Lake of the Woods gets dropped in new GCM filter

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temperature-model-prep#351]
We needed to exclude cells outside of the GCM footprint (#350), but that means that we dropped Lake of the Woods again 😢 I think we should add an exception to the code to fill this missing cell in with data.

![image](https://user-images.githubusercontent.com/13220910/183721648-cc11e198-7672-4961-9ef6-ceb77e686ee3.png)

**Comment by jordansread** [comment]
Agreed sadly. That lake is too well-studied to lose :(
