### ISSUE TITLE
function to figure out which driver data you need based on lat/lon

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#44]
Similar to the one we use for lakes, but simpler. Map lat/lon to NLDAS grid.

**Comment by jread-usgs** [comment]
Don't we have this covered in `cells_containing_points(cell_grid, points)`?

or perhaps a function that calls `cells_containing_points` that you can give lat and lon instead of a point collection?

**Comment by jzwart** [comment]
Yeah, seems like it's covered in `cells_containing_points()` but maybe a more generic function that takes in lat/long would be nice.

**Comment by jread-usgs** [comment]
I have this implemented for a different purpose [here](https://github.com/USGS-R/lake-temperature-model-prep/pull/83/files#diff-d6efbda181b9b4a7e33ac94cdfa613e4R131) but it would be great to have a convenience function too...

**Comment by jread-usgs** [comment]
This is now implemented in 
```yaml
  7_config_merge/out/nml_meteo_fl_values.rds.ind:
    command: munge_meteo_fl(target_name,
      centroids_ind = '2_crosswalk_munge/out/centroid_lakes_sf.rds.ind',
      lake_depth_ind = '7_config_merge/out/nml_lake_depth_values.rds.ind',
      sf_grid = NLDAS_grid,
      time_range = replete_time_range)
```
