### ISSUE TITLE
cooperator data munge in support of expansion to MGLP footprint

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#45]
A list of munging tasks that need to be done to incorporate cooperator data in the expanded footprint (part of #33). 
 
SOUTH DAKOTA

- [ ] Crosswalk between sites in file `SD_Lake_temp_export.xlsx` and our IDs (in this case, MGLP IDs). There is lat/long and good metadata for each lake to do some quality checking. 

- [ ] Track down depth data for `SD_Lake_temp_export.xlsx`. There are zero values for maximum depth for some lakes in tab `Metadata_Max_Depth`. I found a few depth resources for SD: a [thesis ](https://openprairie.sdstate.edu/cgi/viewcontent.cgi?article=1218&context=etd) and a [USGS report](https://pubs.usgs.gov/wri/1984/4030/report.pdf). Or might be able to get some site metadata from the [org's data portal](https://apps.sd.gov/NR92WQMAP/). 

INDIANA

- [ ] Crosswalk between sites and our IDs (in this case, MGLP IDs). This is likely best done using lake metadata in file `Indiana CLP lake data 1994-2013`. In this file, there is lat/long and county info to help ID water bodies. This should cover many lakes in file `Indiana_Glacial_Lakes_WQ_IN_DNR` and `Indiana_GlacialLakes_TempDOprofiles_5.6.13`. 

- [ ] Verify data lakes have depth info. Depth data are included in `Indiana CLP lake data 1994-2013`. 

OTHER
- [ ] Additional cooperator files are currently not being incorporated. These include anything in a sub-folder here. Note that many of these lakes already have data (e.g., the PCA subfolder and Ten Mile Lake subfolder) but in some cases, I know these will add to the record (e.g., Ten Mile missing data in the early 2000s that will be covered by these files).

- [ ] File `Water_Temp.accdb` has negative depths that have not been resolved. The negative depths, according to the explainer file, are ```Water temperature sensor depth. This number is positive if measurement is taken from below the water surface and negative if measurement is taken from lake bottom.``` I confirmed that we cannot easily find what depth from surface this is. That is, -41m is 41 meters from the bottom, and there are no metadata to support figuring out what the site depth is. 

- [ ] The files that end in `historicalfiles_manual` have some clues about sites in the "notes" column. However, some info is not site related. Keywords for sites include `c('basin', 'bay', 'end', 'station', 'WQ')` and likely others. Incorporating this info would help to resolve multiple lake-date-depth values. For now, we assume that multiple lake-date-depth values from these data sources are multiple sites. 

- [ ] The `mendota_temps_long` file has site information in column `Loc`. Additionally, there is an observer column, and in some instances, multiple values per date-depth in Mendota have different observers but NA in the Loc column (I would assume these to be different locations).

**Comment by jread-usgs** [comment]
Was there also some unprocessed LAGOS temperature data available for this expansion too @limnoliver ?

**Comment by limnoliver** [comment]
Yes, see this [subfolder](https://drive.google.com/drive/folders/1nCp5OMWvj0XhebkDiWjMFfoIdsdhnkY-). Looks like there is Illinois, Indiana, and Dakotas data included.

**Comment by jread-usgs** [comment]
Indeed. likely going to require some oversight to prioritize those files. I took a quick look at the "ChemistryResults" file for SD. Looks like AU_IDs correspond to [this](https://denr.sd.gov/dfta/wp/documents/2019laketiers.pdf) set of lake sampling tiers. From that you can get names and counties. From my very light pass, it _seems_ that SD is pretty good about putting these data into the WQP (I looked at SD-BS-L-PICKEREL_01 which is nhdhr_145088870 in our dataset), but there are more recent data from 2014 and 2015 that _aren't_ in the WQP but are in this file. 

I'm guessing it is going to be a state-specific and potentially monitoring-program-specific decision to dig into the effort of matching these state IDs with NHDHR IDs, since we'll want to be at least somewhat confident that we'll gain new data we don't already have from WQP pulls.

**Comment by jread-usgs** [comment]
From our current "status map", it looks like Iowa is really light on temperature data

![image](https://user-images.githubusercontent.com/2349007/78036782-55016280-7330-11ea-88bf-0e5c6967c445.png)

And I don't see any IA data in the LAGOS folders :(

**Comment by jread-usgs** [comment]
We now have ~400 lakes in the Iowa temperature data queue for parsing.

**Comment by jread-usgs** [comment]
Look into 
- [Little Rock lake](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-ntl.248.4)
- [landscape position dataset](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-ntl.95.8)
- [Random Hansen et al 2004](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-ntl.277.2)
- [biocomplexity](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-ntl.41.6)

**Comment by padilla410** [comment]
**WORK IN PROGRESS - DUE 2022-21-04 REVIEWING ISSUE 45 IN LIGHT OF ISSUE 320**


A list of munging tasks that need to be done to incorporate cooperator data in the expanded footprint (part of #33). 
 
SOUTH DAKOTA

- [x] Crosswalk between sites in file `SD_Lake_temp_export.xlsx` and our IDs (in this case, MGLP IDs). There is lat/long and good metadata for each lake to do some quality checking. 
  - *I will be taking care of this when I complete the missing crosswalks highlighted in #267*

- [ ] Track down depth data for `SD_Lake_temp_export.xlsx`. There are zero values for maximum depth for some lakes in tab `Metadata_Max_Depth`. I found a few depth resources for SD: a [thesis ](https://openprairie.sdstate.edu/cgi/viewcontent.cgi?article=1218&context=etd) and a [USGS report](https://pubs.usgs.gov/wri/1984/4030/report.pdf). Or might be able to get some site metadata from the [org's data portal](https://apps.sd.gov/NR92WQMAP/). 
  - *There is temp and depth data included in the `SD_Lake_temp_export.xlsx` data set. I will have to wait until I integrate it into the final data set to check on this. I would advocate against running down more depth data.*
  
INDIANA

- [x] Crosswalk between sites and our IDs (in this case, MGLP IDs). This is likely best done using lake metadata in file `Indiana CLP lake data 1994-2013`. In this file, there is lat/long and county info to help ID water bodies. This should cover many lakes in file `Indiana_Glacial_Lakes_WQ_IN_DNR` and `Indiana_GlacialLakes_TempDOprofiles_5.6.13`. 
  - *I will be taking care of this when I complete the missing crosswalks highlighted in #267*
  
- [ ] Verify data lakes have depth info. Depth data are included in `Indiana CLP lake data 1994-2013`. 
  - *There is temp and depth data included in the `Indiana_Glacial_Lakes_WQ_IN_DNR` data set. I will have to wait until I integrate it into the final data set to check on this. I would advocate against running down more depth data.*

OTHER
- [ ] Additional cooperator files are currently not being incorporated. These include anything in a sub-folder here. Note that many of these lakes already have data (e.g., the PCA subfolder and Ten Mile Lake subfolder) but in some cases, I know these will add to the record (e.g., Ten Mile missing data in the early 2000s that will be covered by these files).
  - *Looks like there is a missing link for `here`. I think we can consider this check box resolved when we close #320*

- [ ] File `Water_Temp.accdb` has negative depths that have not been resolved. The negative depths, according to the explainer file, are ```Water temperature sensor depth. This number is positive if measurement is taken from below the water surface and negative if measurement is taken from lake bottom.``` I confirmed that we cannot easily find what depth from surface this is. That is, -41m is 41 meters from the bottom, and there are no metadata to support figuring out what the site depth is. 
  - *This is still unresolved. These values likely drop out of the pipeline.*

- [ ] The files that end in `historicalfiles_manual` have some clues about sites in the "notes" column. However, some info is not site related. Keywords for sites include `c('basin', 'bay', 'end', 'station', 'WQ')` and likely others. Incorporating this info would help to resolve multiple lake-date-depth values. For now, we assume that multiple lake-date-depth values from these data sources are multiple sites. 

- [ ] The `mendota_temps_long` file has site information in column `Loc`. Additionally, there is an observer column, and in some instances, multiple values per date-depth in Mendota have different observers but NA in the Loc column (I would assume these to be different locations).
