### ISSUE TITLE
new footprint crosswalks not properly using shared cache

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#48]
Not exactly sure what the solution is (yet), but I could not build `wqp_want_lakes` as it kept getting hung up on (already in the shared cache) `1_crosswalk_fetch/out/winslow_lakes_sf.rds.ind`. This is a dependency issue that was solved with a workaround by running 

```
gd_get('1_crosswalk_fetch/out/winslow_lakes_sf.rds.ind')
gd_get('1_crosswalk_fetch/out/lakes_shapefile.prj.ind')
gd_get('1_crosswalk_fetch/out/lakes_shapefile.shx.ind')
gd_get('1_crosswalk_fetch/out/lakes_shapefile.dbf.ind')
```

So it seems the current pipeline does not trigger `gd_get` of the other geo files that need to come along with the shape file. I think I may have been able to just do the last 4 commands, but not sure now. Maybe the easiest solution would be to add the above file to the `depends` field for `1_crosswalk_fetch`.

**Comment by jread-usgs** [comment]
Yes, this becomes easier if we never rely on the individual shapefile files. Instead using the .zip as the target is one way around it too.

**Comment by jread-usgs** [comment]
We no longer rely on these individual files. I think this issue no longer applies.
