### ISSUE TITLE
double build of some targets

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#49]
I think our `scipiper` workflows are causing double builds of some targets. I _thought_ this was going on in the past, but wasn't able to document. When expanding to the new modeling footprint, I was updating the WQP pull. My `wqp_needs` changed which triggered a rebuild of `6_temp_wqp_fetch/inout/wqp_inventory.feather.ind`. The build looked like this: 

![image](https://user-images.githubusercontent.com/15788176/57023783-8ccfc980-6bf8-11e9-928a-1a9e0bbc4a0c.png)

And then moved on to build the partition. The `6_temp_wqp_fetch/inout/wqp_pull_partitions.feather.ind ` build looked like this: 

![image](https://user-images.githubusercontent.com/15788176/57023928-f8199b80-6bf8-11e9-81bf-1322a3fbaa37.png)

which rebuilt the inventory. This isn't a huge issue in this particular place (~400 seconds to rebuild) but could be expensive elsewhere. I have seen this before and suspect it has something to do with our `scipiper` order of operations.

**Comment by jread-usgs** [comment]
I think this is covered in https://github.com/USGS-R/scipiper/issues/115 and https://github.com/USGS-R/scipiper/issues/70
