### ISSUE TITLE
Updating lakeattributes with new lake parameters

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#52]
The glm models access parameters from package [`lakeattributes`](https://github.com/USGS-R/lakeattributes). So to expand the geographic footprint of the models, we need to acquire lake-specific information and export to `lakeattributes`.

I've started to do this in `4_params_munge` by taking the acquired parameters and getting them into `lakeattributes` format. The files that need to be updated are:

In `R/sysdata.rda` (data you can access via `lakeattributes::tablename`) we need to update
- [x] `area`
- [x]  `location` which is lat/long of centroids
- [x] `secchi`
- [x] `zmax`

In other data (data you can access via `data(tablename)`), we need to update
- [x] `canopy`

Other values
- [ ] `elevation` (this is just set to 320 as average across MN-WI-MI so probably don't need to update)
- [ ] `Bathy` data (individual lake files to put [here](https://github.com/USGS-R/lakeattributes/tree/master/inst/Bathy))

**Comment by limnoliver** [comment]
Note for the canopy update: The new calculated canopy values were for the whole footprint, and are missing 152 values for lakes that were present in the Winslow et al canopy data frame. For the other 8751 that are in both datasets, 426 values are different when comparing the Winslow and new calculated canopy heights. 

Based on this info, I'm going to append just the `mglp` lakes to the old canopy dataset.

**Comment by jzwart** [comment]
> 426 values are different when comparing the Winslow and new calculated canopy heights.

How different were the new canopy heights? Far off or pretty close?

**Comment by limnoliver** [comment]
![image](https://user-images.githubusercontent.com/15788176/57239575-dd2c9a00-6ff1-11e9-8a2d-bbfbdd79bbbf.png)

**Comment by limnoliver** [comment]
Note for the secchi update: I could not get the secchi data to build within `lakeattributes` from the data files in[ `data-raw`](https://github.com/USGS-R/lakeattributes/tree/master/data-raw/secchi). I kept getting error: 
```
![image](https://user-images.githubusercontent.com/15788176/57240584-7492ec80-6ff4-11e9-93c4-7d6faa76e834.png)
```
Likely because I did not have the LAGOS_KEY locally. This should be fixed down the road. In the meantime, I archived the old secchi data as `secchi_v1.0.rds` and appended the new data to that.

**Comment by limnoliver** [comment]
Now that I've figured out how to update `lakeattributes`, stashing this info here for future reference:

1. Fork `lakeattributes` and either create a new branch, or fork an existing "update" branch if it hasn't been merged.

2. Copy over `lakeattributes_area`, `lakeattributes_location`, `lakeattributes_secchi`, `lakeattributes_depth`, and `lakeattributes_canopy` rds files from [lake-model-data-prep](https://github.com/USGS-R/lake-temperature-model-prep) pipeline into the appropriate subfolders of [`data-raw`](https://github.com/USGS-R/lakeattributes/tree/master/data-raw)

3. Run code in `update_all.R` and then `make()` to add zmax.

4. Rebuild, commit changes, and push!

**Comment by jread-usgs** [comment]
replaced with #78
