### ISSUE TITLE
switch from centroid to "pole of inaccessibility of a polygon" (or something like that)

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#55]
This helps us avoid the common issue of our single lat/lon location of a lake being outside of a lake, or in rare cases, within another lake. see [R package](https://cran.r-project.org/web/packages/polylabelr/index.html) and [original code](https://github.com/mapbox/polylabel)

**Comment by jread-usgs** [comment]
This could be a drop in replacement for how we use [centroids](https://github.com/USGS-R/lake-temperature-model-prep/blob/2dab96b545b71d5b9dacff43524e558412d1116b/6_drivers_fetch.yml#L45)

**Comment by jread-usgs** [comment]
This isn't as simple as it looks. That existing package doesn't directly support spatial features, and the whole donuts, multi-polygons, lions, tigers, bears, oh my seem like things that wouldn't be handled unless they are split out per polygon, which is a bunch of extra coding.

**Comment by lindsayplatt** [comment]
Wondering if this would solve some of this issues noted in #289 due to sinuous reservoirs?

**Comment by jread-usgs** [comment]
If we used LAGOS as the starting point for lake features (instead of NHD), we could use their lat/lon data which would be of this type and solve this issue. We'd get this (and elevation) for free in that case.
