### ISSUE TITLE
Make these updates in next PR

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#56]
1. Pull out `crs = 4326` and put as variable in config -- currently is a "magic number" [as Jake points out](https://github.com/USGS-R/lake-temperature-model-prep/pull/54).

**Comment by jread-usgs** [comment]
I think this is only [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/2b16ee99612814efe4b7c077f4373c1b79989676/1_crosswalk_fetch/src/munge_crosswalk.R#L33) and [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/2b16ee99612814efe4b7c077f4373c1b79989676/1_crosswalk_fetch/src/munge_crosswalk.R#L55)
