### ISSUE TITLE
GLM questions about Kw 

### ISSUE THREAD

**Issue by gferrari844** [USGS-R/lake-temperature-model-prep#58]
While computing the .nml file that will allow me to run the application I read on some papers that one of the best option that we can introduce (i'm using the 3.0 version) is the implementation of the Kw as time series file; unfortunately we didn’t finds any operative instruction to do that. I read that I simply have to recal a Kw_file=[string] with a daily time series but got an error back (“Kd not found”). 
Does someone know how to implement properly this function? 
Thank you in advance for your precious help

### ### Giacomo

**Comment by jread-usgs** [comment]
this issue was tested by gferrari844 and worked. Response was in email.
