### ISSUE TITLE
Verify there are no leading zeros in DOW numbers

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#59]
Sometimes DOWs have leading zeros. Does not look like our crosswalk has leading zeros, but we should double check that imported cooperator data with DOW numbers is being handled in the same way.

**Comment by limnoliver** [comment]
DOWs are 8 characters long. If you end up with a DOW of 7 characters, add a leading zero.

**Comment by lindsayplatt** [comment]
Trying to follow up on this, not entirely sure where one needs to check, but looked at the coop data in `7a_temp_coop_munge` and don't see any with less than 7 characters:

```r
library(scipiper)
library(tidyverse)

coop_in <- sc_retrieve('7a_temp_coop_munge/out/all_coop_dat_linked.feather.ind')
coop_dat <- feather::read_feather(coop_in)

coop_dat %>% 
  filter(state_id_type == "DOW") %>% 
  filter(nchar(state_id) < 7)

# A tibble: 0 x 20
# ... with 20 variables: DateTime <date>, depth <dbl>, temp <dbl>, source <chr>,
#   site <chr>, time <chr>, timezone <chr>, Timezone <chr>, TimeZone <chr>,
#   site_id <chr>, Lake Name <chr>, County <chr>, Zone <chr>, STORET ID <chr>,
#   FID <dbl>, Id <dbl>, Site <chr>, Notes <chr>, state_id_type <chr>,
#   state_id <chr>
```
