### ISSUE TITLE
unclear if we need 2_crosswalk_munge/out/feature_crosswalk.rds or just the crosswalk table for WQP pulls

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#66]
@limnoliver I might need to talk this one through. We have a WQP monitoring ID to NHDHR permID crosswalk, but then we also make a points feature collection that joins the two, adding a field for `site_id` and other things that are in the lake feature shapefile. 

I'm wondering if we need this second set of features, or if we are simply good to go with the crosswalk file that tells us what WQP IDs are to be pulled and also which NHDHR IDs those correspond to. The spatial data comes in [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/729f32cf93c07cb9091a122db42b948e49fcba65/6_temp_wqp_fetch.yml#L30) but I think it is just filtered to get monitoring IDs, which we could get from the crosswalk .rds instead. But I might be oversimplifying this. Just looking to see if I need to propagate this target in the overhaul in #53

**Comment by limnoliver** [comment]
@jread-usgs I think your interpretation is correct here - that we just need the table and not the shapefiles.
