### ISSUE TITLE
add secchi sources from Kelsey's aggregation

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#97]
See email from @vitensek on 10/31

**Comment by jread-usgs** [comment]
For our `8_viz` stage, it looks like there are 15 lakes that have time varying Kd but no single secchi (or Kd/Kw) value in the pipeline

![image](https://user-images.githubusercontent.com/2349007/77832171-02426380-7102-11ea-871b-7447d02133ba.png)

Since Kelsey's models require a _ton_ of secchi data to be included, we're likely missing some key sources.

**Comment by jread-usgs** [comment]
and see #111

**Comment by lindsayplatt** [comment]
In most recent status map, there are no sites with a kw file but no static kd/kw value. So, this seems like it was resolved at some point.

![image](https://user-images.githubusercontent.com/13220910/159777390-63216b78-04ea-4b90-90b5-b0245d93bb17.png)
