### ISSUE TITLE
DOW to NHDHR issues

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#98]
@aappling-usgs noticed that some lakes in our original 68-lake dataset weren't making the cut (temperature observations at >5 depths on >200 dates) anymore. For example, Rainy Lake has only 185 days of observation in our dataset. Below are all lakes that were in the original 68 lakes but no longer show up as meeting those criteria:

```  site_id         WINSLOW_ID    lake_name      latitude longitude maxdepth meandepth area_km2 kd_avg
  <chr>           <chr>         <chr>             <dbl>     <dbl>    <dbl>     <dbl>    <dbl>  <dbl>
1 nhdhr_120019354 nhd_120052233 Rainy Lake         48.6     -93.0     54         9.8   197.     0.76
2 nhdhr_157361961 nhd_120052587 Petenwell Lake     44.1     -90.0     13.4      NA      96.3    1.89
3 nhdhr_151951149 nhd_120053694 Tainter Lake       45.0     -91.8     11.3      NA       5.26   1.47
4 nhdhr_139269431 nhd_12162854  Cedar Lake (2)     43.4     -88.3     32        NA       3.76   0.52
5 nhdhr_70331799  nhd_13393533  Found Lake         46.0     -89.5      6.4       3.1     1.36   0.43
6 nhdhr_70332035  nhd_13393567  Towanda Lake       45.9     -89.7      8.2      NA       0.54   0.61
7 nhdhr_75651507  nhd_9022741   Lake Lucerne       45.5     -88.8     22.3      NA       4.16   0.22
```
I knew this was wrong -- we have SO MUCH Rainy data in the cooperator files. Tracing some things backwards, I noticed it's an issue of the DOW crosswalk.

Based on the `winslow_nhdhr_xwalk.rds`, the old Rainy Lake ID (`nhd_120052233`) equates to the new ID `nhdhr_120019354`.  However, from the DOW crosswalk, the DOW for Rainy from the cooperator files (`69069400`) is associated with `nhdhr_EBD8B5AF-7EBC-43A3-82BA-AF41830C144C`. 

~~This seems ok in that the old Rainy ID may have been translated to multiple new Rainy IDs. However, the new ID that most of the data is associated with does not exist in our `lakes_sf.rds`, so won't be connected to any other data downstream. Likewise, the new nhdhr for Rainy does not exist in the DOW crosswalk.~~

My guess is this has something to do with how the DOW crosswalk is being generated, or how multi-basin lakes are being handled, but I can't track down the specific problem. Any ideas @jread-usgs?

**Comment by aappling-usgs** [comment]
Here are the current observation counts for those site_ids:
```
  site_id         n_obs_dates
  <chr>                 <int>
1 nhdhr_120019354         185
2 nhdhr_139269431         123
3 nhdhr_151951149          22
4 nhdhr_157361961          23
5 nhdhr_70331799            0
6 nhdhr_70332035            0
7 nhdhr_75651507           21
```

**Comment by limnoliver** [comment]
OK - scratch some of this! First, the new ID `nhdhr_EBD8B5AF-7EBC-43A3-82BA-AF41830C144C` IS in the new lakes list (was using an old one!). So the issue isn't as scary as it was 5 minutes ago. 

BUT -- it does still present issues with going back and forth between old and new data.

**Comment by jread-usgs** [comment]
I think we understand and accept the things described within this issue and the impact is smaller now that we've moved to HR fully.
